package com.jyd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseHrEmployee<M extends BaseHrEmployee<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setDepartmentId(java.lang.Integer departmentId) {
		set("department_id", departmentId);
		return (M)this;
	}
	
	public java.lang.Integer getDepartmentId() {
		return getInt("department_id");
	}

	public M setHeadDepartmentId(java.lang.Integer headDepartmentId) {
		set("head_department_id", headDepartmentId);
		return (M)this;
	}
	
	public java.lang.Integer getHeadDepartmentId() {
		return getInt("head_department_id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setSex(java.lang.Integer sex) {
		set("sex", sex);
		return (M)this;
	}
	
	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	public M setPositionId(java.lang.Integer positionId) {
		set("position_id", positionId);
		return (M)this;
	}
	
	public java.lang.Integer getPositionId() {
		return getInt("position_id");
	}

	public M setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
		return (M)this;
	}
	
	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public M setIdNo(java.lang.String idNo) {
		set("id_no", idNo);
		return (M)this;
	}
	
	public java.lang.String getIdNo() {
		return getStr("id_no");
	}

	public M setPhoto(java.lang.String photo) {
		set("photo", photo);
		return (M)this;
	}
	
	public java.lang.String getPhoto() {
		return getStr("photo");
	}

	public M setEntryDate(java.util.Date entryDate) {
		set("entry_date", entryDate);
		return (M)this;
	}
	
	public java.util.Date getEntryDate() {
		return get("entry_date");
	}

	public M setObtainmentDate(java.util.Date obtainmentDate) {
		set("obtainment_date", obtainmentDate);
		return (M)this;
	}
	
	public java.util.Date getObtainmentDate() {
		return get("obtainment_date");
	}

	public M setFertilityState(java.lang.Integer fertilityState) {
		set("fertility_state", fertilityState);
		return (M)this;
	}
	
	public java.lang.Integer getFertilityState() {
		return getInt("fertility_state");
	}

	public M setPoliticalStatus(java.lang.String politicalStatus) {
		set("political_status", politicalStatus);
		return (M)this;
	}
	
	public java.lang.String getPoliticalStatus() {
		return getStr("political_status");
	}

	public M setEducationId(java.lang.Integer educationId) {
		set("education_id", educationId);
		return (M)this;
	}
	
	public java.lang.Integer getEducationId() {
		return getInt("education_id");
	}

	public M setGraduateSchool(java.lang.String graduateSchool) {
		set("graduate_school", graduateSchool);
		return (M)this;
	}
	
	public java.lang.String getGraduateSchool() {
		return getStr("graduate_school");
	}

	public M setMajors(java.lang.String majors) {
		set("majors", majors);
		return (M)this;
	}
	
	public java.lang.String getMajors() {
		return getStr("majors");
	}

	public M setGraduationDate(java.util.Date graduationDate) {
		set("graduation_date", graduationDate);
		return (M)this;
	}
	
	public java.util.Date getGraduationDate() {
		return get("graduation_date");
	}

	public M setWorkDate(java.util.Date workDate) {
		set("work_date", workDate);
		return (M)this;
	}
	
	public java.util.Date getWorkDate() {
		return get("work_date");
	}

	public M setNativePlace(java.lang.String nativePlace) {
		set("native_place", nativePlace);
		return (M)this;
	}
	
	public java.lang.String getNativePlace() {
		return getStr("native_place");
	}

	public M setHouseholdRegistrationAdress(java.lang.String householdRegistrationAdress) {
		set("household_registration_adress", householdRegistrationAdress);
		return (M)this;
	}
	
	public java.lang.String getHouseholdRegistrationAdress() {
		return getStr("household_registration_adress");
	}

	public M setCurrentAddress(java.lang.String currentAddress) {
		set("current_address", currentAddress);
		return (M)this;
	}
	
	public java.lang.String getCurrentAddress() {
		return getStr("current_address");
	}

	public M setContactInformation(java.lang.String contactInformation) {
		set("contact_information", contactInformation);
		return (M)this;
	}
	
	public java.lang.String getContactInformation() {
		return getStr("contact_information");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setBankCardNo(java.lang.String bankCardNo) {
		set("bank_card_no", bankCardNo);
		return (M)this;
	}
	
	public java.lang.String getBankCardNo() {
		return getStr("bank_card_no");
	}

	public M setReferees(java.lang.String referees) {
		set("referees", referees);
		return (M)this;
	}
	
	public java.lang.String getReferees() {
		return getStr("referees");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setLeaveTime(java.util.Date leaveTime) {
		set("leave_time", leaveTime);
		return (M)this;
	}
	
	public java.util.Date getLeaveTime() {
		return get("leave_time");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setBankName(java.lang.String bankName) {
		set("bank_name", bankName);
		return (M)this;
	}
	
	public java.lang.String getBankName() {
		return getStr("bank_name");
	}

	public M setPapers(java.lang.Integer papers) {
		set("papers", papers);
		return (M)this;
	}
	
	public java.lang.Integer getPapers() {
		return getInt("papers");
	}

	public M setEffectiveDate(java.util.Date effectiveDate) {
		set("effective_date", effectiveDate);
		return (M)this;
	}
	
	public java.util.Date getEffectiveDate() {
		return get("effective_date");
	}

	public M setDirector(java.lang.Integer director) {
		set("director", director);
		return (M)this;
	}
	
	public java.lang.Integer getDirector() {
		return getInt("director");
	}

	public M setShiftState(java.lang.Integer shiftState) {
		set("shift_state", shiftState);
		return (M)this;
	}
	
	public java.lang.Integer getShiftState() {
		return getInt("shift_state");
	}

	public M setEmployeePropertiesId(java.lang.Integer employeePropertiesId) {
		set("employee_properties_id", employeePropertiesId);
		return (M)this;
	}
	
	public java.lang.Integer getEmployeePropertiesId() {
		return getInt("employee_properties_id");
	}

	public M setFormalType(java.lang.Integer formalType) {
		set("formal_type", formalType);
		return (M)this;
	}
	
	public java.lang.Integer getFormalType() {
		return getInt("formal_type");
	}

}
