package com.jyd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysMenu<M extends BaseSysMenu<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setMenuId(java.lang.String menuId) {
		set("menu_id", menuId);
		return (M)this;
	}
	
	public java.lang.String getMenuId() {
		return getStr("menu_id");
	}

	public M setParentId(java.lang.String parentId) {
		set("parent_id", parentId);
		return (M)this;
	}
	
	public java.lang.String getParentId() {
		return getStr("parent_id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setIconName(java.lang.String iconName) {
		set("icon_name", iconName);
		return (M)this;
	}
	
	public java.lang.String getIconName() {
		return getStr("icon_name");
	}

	public M setMenuUrl(java.lang.String menuUrl) {
		set("menu_url", menuUrl);
		return (M)this;
	}
	
	public java.lang.String getMenuUrl() {
		return getStr("menu_url");
	}

	public M setCallMethod(java.lang.String callMethod) {
		set("call_method", callMethod);
		return (M)this;
	}
	
	public java.lang.String getCallMethod() {
		return getStr("call_method");
	}

	public M setLanguageId(java.lang.String languageId) {
		set("language_id", languageId);
		return (M)this;
	}
	
	public java.lang.String getLanguageId() {
		return getStr("language_id");
	}

	public M setDisplay(java.lang.Integer display) {
		set("display", display);
		return (M)this;
	}
	
	public java.lang.Integer getDisplay() {
		return getInt("display");
	}

	public M setSort(java.lang.Float sort) {
		set("sort", sort);
		return (M)this;
	}
	
	public java.lang.Float getSort() {
		return getFloat("sort");
	}

}
