package com.jyd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWfFormSetSalaryV1<M extends BaseWfFormSetSalaryV1<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setEmployeeId(java.lang.Integer employeeId) {
		set("employee_id", employeeId);
		return (M)this;
	}
	
	public java.lang.Integer getEmployeeId() {
		return getInt("employee_id");
	}

	public M setBeforeSalaryStructureId(java.lang.Integer beforeSalaryStructureId) {
		set("before_salary_structure_id", beforeSalaryStructureId);
		return (M)this;
	}
	
	public java.lang.Integer getBeforeSalaryStructureId() {
		return getInt("before_salary_structure_id");
	}

	public M setBeforeSalaryLevelId(java.lang.Integer beforeSalaryLevelId) {
		set("before_salary_level_id", beforeSalaryLevelId);
		return (M)this;
	}
	
	public java.lang.Integer getBeforeSalaryLevelId() {
		return getInt("before_salary_level_id");
	}

	public M setBeforeTotalSalary(java.lang.Double beforeTotalSalary) {
		set("before_total_salary", beforeTotalSalary);
		return (M)this;
	}
	
	public java.lang.Double getBeforeTotalSalary() {
		return getDouble("before_total_salary");
	}

	public M setAfterSalaryStructureId(java.lang.Integer afterSalaryStructureId) {
		set("after_salary_structure_id", afterSalaryStructureId);
		return (M)this;
	}
	
	public java.lang.Integer getAfterSalaryStructureId() {
		return getInt("after_salary_structure_id");
	}

	public M setAfterSalaryLevelId(java.lang.Integer afterSalaryLevelId) {
		set("after_salary_level_id", afterSalaryLevelId);
		return (M)this;
	}
	
	public java.lang.Integer getAfterSalaryLevelId() {
		return getInt("after_salary_level_id");
	}

	public M setAfterTotalSalary(java.lang.Double afterTotalSalary) {
		set("after_total_salary", afterTotalSalary);
		return (M)this;
	}
	
	public java.lang.Double getAfterTotalSalary() {
		return getDouble("after_total_salary");
	}

	public M setDataKey(java.lang.String dataKey) {
		set("data_key", dataKey);
		return (M)this;
	}
	
	public java.lang.String getDataKey() {
		return getStr("data_key");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

}
