package com.jyd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCusContractStageFeeRepayment<M extends BaseCusContractStageFeeRepayment<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCusContractStageFeeId(java.lang.Integer cusContractStageFeeId) {
		set("cus_contract_stage_fee_id", cusContractStageFeeId);
		return (M)this;
	}
	
	public java.lang.Integer getCusContractStageFeeId() {
		return getInt("cus_contract_stage_fee_id");
	}

	public M setExpendValue(java.math.BigDecimal expendValue) {
		set("expend_value", expendValue);
		return (M)this;
	}
	
	public java.math.BigDecimal getExpendValue() {
		return get("expend_value");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setIsLock(java.lang.Integer isLock) {
		set("is_lock", isLock);
		return (M)this;
	}
	
	public java.lang.Integer getIsLock() {
		return getInt("is_lock");
	}

	public M setLockUser(java.lang.String lockUser) {
		set("lock_user", lockUser);
		return (M)this;
	}
	
	public java.lang.String getLockUser() {
		return getStr("lock_user");
	}

}
