package com.jyd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWfFormContractFaceTrialV3<M extends BaseWfFormContractFaceTrialV3<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setContractId(java.lang.Integer contractId) {
		set("contract_id", contractId);
		return (M)this;
	}
	
	public java.lang.Integer getContractId() {
		return getInt("contract_id");
	}

	public M setCompanyBussiness(java.lang.String companyBussiness) {
		set("company_bussiness", companyBussiness);
		return (M)this;
	}
	
	public java.lang.String getCompanyBussiness() {
		return getStr("company_bussiness");
	}

	public M setMonthSaleRoom(java.lang.Double monthSaleRoom) {
		set("month_sale_room", monthSaleRoom);
		return (M)this;
	}
	
	public java.lang.Double getMonthSaleRoom() {
		return getDouble("month_sale_room");
	}

	public M setMachine(java.lang.Double machine) {
		set("machine", machine);
		return (M)this;
	}
	
	public java.lang.Double getMachine() {
		return getDouble("machine");
	}

	public M setGrossProfitRate(java.lang.Double grossProfitRate) {
		set("gross_profit_rate", grossProfitRate);
		return (M)this;
	}
	
	public java.lang.Double getGrossProfitRate() {
		return getDouble("gross_profit_rate");
	}

	public M setStoreMaterial(java.lang.Double storeMaterial) {
		set("store_material", storeMaterial);
		return (M)this;
	}
	
	public java.lang.Double getStoreMaterial() {
		return getDouble("store_material");
	}

	public M setEmployeeWage(java.lang.Double employeeWage) {
		set("employee_wage", employeeWage);
		return (M)this;
	}
	
	public java.lang.Double getEmployeeWage() {
		return getDouble("employee_wage");
	}

	public M setTotalEmployee(java.lang.Integer totalEmployee) {
		set("total_employee", totalEmployee);
		return (M)this;
	}
	
	public java.lang.Integer getTotalEmployee() {
		return getInt("total_employee");
	}

	public M setAccountReceivable(java.lang.Double accountReceivable) {
		set("account_receivable", accountReceivable);
		return (M)this;
	}
	
	public java.lang.Double getAccountReceivable() {
		return getDouble("account_receivable");
	}

	public M setAccountPayable(java.lang.Double accountPayable) {
		set("account_payable", accountPayable);
		return (M)this;
	}
	
	public java.lang.Double getAccountPayable() {
		return getDouble("account_payable");
	}

	public M setPlaceRental(java.lang.Double placeRental) {
		set("place_rental", placeRental);
		return (M)this;
	}
	
	public java.lang.Double getPlaceRental() {
		return getDouble("place_rental");
	}

	public M setPlaceArea(java.lang.Double placeArea) {
		set("place_area", placeArea);
		return (M)this;
	}
	
	public java.lang.Double getPlaceArea() {
		return getDouble("place_area");
	}

	public M setOtherCharge(java.lang.Double otherCharge) {
		set("other_charge", otherCharge);
		return (M)this;
	}
	
	public java.lang.Double getOtherCharge() {
		return getDouble("other_charge");
	}

	public M setProfit(java.lang.Double profit) {
		set("profit", profit);
		return (M)this;
	}
	
	public java.lang.Double getProfit() {
		return getDouble("profit");
	}

	public M setCompanyNature(java.lang.String companyNature) {
		set("company_nature", companyNature);
		return (M)this;
	}
	
	public java.lang.String getCompanyNature() {
		return getStr("company_nature");
	}

	public M setCompanyScale(java.lang.String companyScale) {
		set("company_scale", companyScale);
		return (M)this;
	}
	
	public java.lang.String getCompanyScale() {
		return getStr("company_scale");
	}

	public M setIndustry(java.lang.String industry) {
		set("industry", industry);
		return (M)this;
	}
	
	public java.lang.String getIndustry() {
		return getStr("industry");
	}

	public M setDepartment(java.lang.String department) {
		set("department", department);
		return (M)this;
	}
	
	public java.lang.String getDepartment() {
		return getStr("department");
	}

	public M setPosition(java.lang.String position) {
		set("position", position);
		return (M)this;
	}
	
	public java.lang.String getPosition() {
		return getStr("position");
	}

	public M setDuty(java.lang.String duty) {
		set("duty", duty);
		return (M)this;
	}
	
	public java.lang.String getDuty() {
		return getStr("duty");
	}

	public M setSalary(java.lang.Double salary) {
		set("salary", salary);
		return (M)this;
	}
	
	public java.lang.Double getSalary() {
		return getDouble("salary");
	}

	public M setOtherEarning(java.lang.Double otherEarning) {
		set("other_earning", otherEarning);
		return (M)this;
	}
	
	public java.lang.Double getOtherEarning() {
		return getDouble("other_earning");
	}

	public M setJoinDate(java.util.Date joinDate) {
		set("join_date", joinDate);
		return (M)this;
	}
	
	public java.util.Date getJoinDate() {
		return get("join_date");
	}

	public M setSalaryDate(java.lang.Integer salaryDate) {
		set("salary_date", salaryDate);
		return (M)this;
	}
	
	public java.lang.Integer getSalaryDate() {
		return getInt("salary_date");
	}

	public M setChildRemark(java.lang.String childRemark) {
		set("child_remark", childRemark);
		return (M)this;
	}
	
	public java.lang.String getChildRemark() {
		return getStr("child_remark");
	}

	public M setMateRemark(java.lang.String mateRemark) {
		set("mate_remark", mateRemark);
		return (M)this;
	}
	
	public java.lang.String getMateRemark() {
		return getStr("mate_remark");
	}

	public M setPersonalRemark(java.lang.String personalRemark) {
		set("personal_remark", personalRemark);
		return (M)this;
	}
	
	public java.lang.String getPersonalRemark() {
		return getStr("personal_remark");
	}

	public M setHousePropertyOne(java.lang.Double housePropertyOne) {
		set("house_property_one", housePropertyOne);
		return (M)this;
	}
	
	public java.lang.Double getHousePropertyOne() {
		return getDouble("house_property_one");
	}

	public M setHouseAreaOne(java.lang.Double houseAreaOne) {
		set("house_area_one", houseAreaOne);
		return (M)this;
	}
	
	public java.lang.Double getHouseAreaOne() {
		return getDouble("house_area_one");
	}

	public M setHouseOneAmountInArear(java.lang.Double houseOneAmountInArear) {
		set("house_one_amount_in_arear", houseOneAmountInArear);
		return (M)this;
	}
	
	public java.lang.Double getHouseOneAmountInArear() {
		return getDouble("house_one_amount_in_arear");
	}

	public M setHousePropertyTwo(java.lang.Double housePropertyTwo) {
		set("house_property_two", housePropertyTwo);
		return (M)this;
	}
	
	public java.lang.Double getHousePropertyTwo() {
		return getDouble("house_property_two");
	}

	public M setHouseAreaTwo(java.lang.Double houseAreaTwo) {
		set("house_area_two", houseAreaTwo);
		return (M)this;
	}
	
	public java.lang.Double getHouseAreaTwo() {
		return getDouble("house_area_two");
	}

	public M setHouseTwoAmountInArear(java.lang.Double houseTwoAmountInArear) {
		set("house_two_amount_in_arear", houseTwoAmountInArear);
		return (M)this;
	}
	
	public java.lang.Double getHouseTwoAmountInArear() {
		return getDouble("house_two_amount_in_arear");
	}

	public M setCarBrandOne(java.lang.String carBrandOne) {
		set("car_brand_one", carBrandOne);
		return (M)this;
	}
	
	public java.lang.String getCarBrandOne() {
		return getStr("car_brand_one");
	}

	public M setCarMarketPriceOne(java.lang.Double carMarketPriceOne) {
		set("car_market_price_one", carMarketPriceOne);
		return (M)this;
	}
	
	public java.lang.Double getCarMarketPriceOne() {
		return getDouble("car_market_price_one");
	}

	public M setCarOneAmountInArear(java.lang.Double carOneAmountInArear) {
		set("car_one_amount_in_arear", carOneAmountInArear);
		return (M)this;
	}
	
	public java.lang.Double getCarOneAmountInArear() {
		return getDouble("car_one_amount_in_arear");
	}

	public M setCarBrandTwo(java.lang.String carBrandTwo) {
		set("car_brand_two", carBrandTwo);
		return (M)this;
	}
	
	public java.lang.String getCarBrandTwo() {
		return getStr("car_brand_two");
	}

	public M setCarMarketPriceTwo(java.lang.Double carMarketPriceTwo) {
		set("car_market_price_two", carMarketPriceTwo);
		return (M)this;
	}
	
	public java.lang.Double getCarMarketPriceTwo() {
		return getDouble("car_market_price_two");
	}

	public M setCarTwoAmountInArear(java.lang.Double carTwoAmountInArear) {
		set("car_two_amount_in_arear", carTwoAmountInArear);
		return (M)this;
	}
	
	public java.lang.Double getCarTwoAmountInArear() {
		return getDouble("car_two_amount_in_arear");
	}

	public M setCreditCardBankNameOne(java.lang.String creditCardBankNameOne) {
		set("credit_card_bank_name_one", creditCardBankNameOne);
		return (M)this;
	}
	
	public java.lang.String getCreditCardBankNameOne() {
		return getStr("credit_card_bank_name_one");
	}

	public M setLimitOne(java.lang.Double limitOne) {
		set("limit_one", limitOne);
		return (M)this;
	}
	
	public java.lang.Double getLimitOne() {
		return getDouble("limit_one");
	}

	public M setCreditCardOneAmountInArear(java.lang.Double creditCardOneAmountInArear) {
		set("credit_card_one_amount_in_arear", creditCardOneAmountInArear);
		return (M)this;
	}
	
	public java.lang.Double getCreditCardOneAmountInArear() {
		return getDouble("credit_card_one_amount_in_arear");
	}

	public M setCreditCardBankNameTwo(java.lang.String creditCardBankNameTwo) {
		set("credit_card_bank_name_two", creditCardBankNameTwo);
		return (M)this;
	}
	
	public java.lang.String getCreditCardBankNameTwo() {
		return getStr("credit_card_bank_name_two");
	}

	public M setLimitTwo(java.lang.Double limitTwo) {
		set("limit_two", limitTwo);
		return (M)this;
	}
	
	public java.lang.Double getLimitTwo() {
		return getDouble("limit_two");
	}

	public M setCreditCardTwoAmountInArear(java.lang.Double creditCardTwoAmountInArear) {
		set("credit_card_two_amount_in_arear", creditCardTwoAmountInArear);
		return (M)this;
	}
	
	public java.lang.Double getCreditCardTwoAmountInArear() {
		return getDouble("credit_card_two_amount_in_arear");
	}

	public M setTotalLimit(java.lang.Double totalLimit) {
		set("total_limit", totalLimit);
		return (M)this;
	}
	
	public java.lang.Double getTotalLimit() {
		return getDouble("total_limit");
	}

	public M setTotalAmountInArear(java.lang.Double totalAmountInArear) {
		set("total_amount_in_arear", totalAmountInArear);
		return (M)this;
	}
	
	public java.lang.Double getTotalAmountInArear() {
		return getDouble("total_amount_in_arear");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setHomeVisitCheck(java.lang.String homeVisitCheck) {
		set("home_visit_check", homeVisitCheck);
		return (M)this;
	}
	
	public java.lang.String getHomeVisitCheck() {
		return getStr("home_visit_check");
	}

	public M setPropertyOne(java.lang.Integer propertyOne) {
		set("property_one", propertyOne);
		return (M)this;
	}
	
	public java.lang.Integer getPropertyOne() {
		return getInt("property_one");
	}

	public M setPropertyTwo(java.lang.Integer propertyTwo) {
		set("property_two", propertyTwo);
		return (M)this;
	}
	
	public java.lang.Integer getPropertyTwo() {
		return getInt("property_two");
	}

	public M setMortgageRepayDate(java.util.Date mortgageRepayDate) {
		set("mortgage_repay_date", mortgageRepayDate);
		return (M)this;
	}
	
	public java.util.Date getMortgageRepayDate() {
		return get("mortgage_repay_date");
	}

	public M setMortgageMaturityDate(java.util.Date mortgageMaturityDate) {
		set("mortgage_maturity_date", mortgageMaturityDate);
		return (M)this;
	}
	
	public java.util.Date getMortgageMaturityDate() {
		return get("mortgage_maturity_date");
	}

}
