package com.jyd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBaUploadFileType<M extends BaseBaUploadFileType<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUploadFileType(java.lang.String uploadFileType) {
		set("upload_file_type", uploadFileType);
		return (M)this;
	}
	
	public java.lang.String getUploadFileType() {
		return getStr("upload_file_type");
	}

	public M setExtension(java.lang.String extension) {
		set("extension", extension);
		return (M)this;
	}
	
	public java.lang.String getExtension() {
		return getStr("extension");
	}

	public M setMaxSize(java.lang.Integer maxSize) {
		set("max_size", maxSize);
		return (M)this;
	}
	
	public java.lang.Integer getMaxSize() {
		return getInt("max_size");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setFormId(java.lang.Integer formId) {
		set("form_id", formId);
		return (M)this;
	}
	
	public java.lang.Integer getFormId() {
		return getInt("form_id");
	}

	public M setSortIndex(java.lang.Integer sortIndex) {
		set("sort_index", sortIndex);
		return (M)this;
	}
	
	public java.lang.Integer getSortIndex() {
		return getInt("sort_index");
	}

}
