package com.jyd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCusThirdpartTongdunCustomerCredit<M extends BaseCusThirdpartTongdunCustomerCredit<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setIdCard(java.lang.String idCard) {
		set("id_card", idCard);
		return (M)this;
	}
	
	public java.lang.String getIdCard() {
		return getStr("id_card");
	}

	public M setMobilephone(java.lang.String mobilephone) {
		set("mobilephone", mobilephone);
		return (M)this;
	}
	
	public java.lang.String getMobilephone() {
		return getStr("mobilephone");
	}

	public M setQueryDate(java.util.Date queryDate) {
		set("query_date", queryDate);
		return (M)this;
	}
	
	public java.util.Date getQueryDate() {
		return get("query_date");
	}

	public M setHtmlsrc(java.lang.String htmlsrc) {
		set("htmlsrc", htmlsrc);
		return (M)this;
	}
	
	public java.lang.String getHtmlsrc() {
		return getStr("htmlsrc");
	}

}
