package com.jyd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWfWorkFlowTypeFlow<M extends BaseWfWorkFlowTypeFlow<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setWorkFlowTypeId(java.lang.Integer workFlowTypeId) {
		set("work_flow_type_id", workFlowTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getWorkFlowTypeId() {
		return getInt("work_flow_type_id");
	}

	public M setWorkFlowTypeFlowName(java.lang.String workFlowTypeFlowName) {
		set("work_flow_type_flow_name", workFlowTypeFlowName);
		return (M)this;
	}
	
	public java.lang.String getWorkFlowTypeFlowName() {
		return getStr("work_flow_type_flow_name");
	}

	public M setFormId(java.lang.Integer formId) {
		set("form_id", formId);
		return (M)this;
	}
	
	public java.lang.Integer getFormId() {
		return getInt("form_id");
	}

	public M setFlowId(java.lang.Integer flowId) {
		set("flow_id", flowId);
		return (M)this;
	}
	
	public java.lang.Integer getFlowId() {
		return getInt("flow_id");
	}

	public M setNeed(java.lang.Integer need) {
		set("need", need);
		return (M)this;
	}
	
	public java.lang.Integer getNeed() {
		return getInt("need");
	}

	public M setDecision(java.lang.Integer decision) {
		set("decision", decision);
		return (M)this;
	}
	
	public java.lang.Integer getDecision() {
		return getInt("decision");
	}

	public M setSortIndex(java.lang.Integer sortIndex) {
		set("sort_index", sortIndex);
		return (M)this;
	}
	
	public java.lang.Integer getSortIndex() {
		return getInt("sort_index");
	}

	public M setDistinctStore(java.lang.Integer distinctStore) {
		set("distinct_store", distinctStore);
		return (M)this;
	}
	
	public java.lang.Integer getDistinctStore() {
		return getInt("distinct_store");
	}

	public M setEntryDepartment(java.lang.Integer entryDepartment) {
		set("entry_department", entryDepartment);
		return (M)this;
	}
	
	public java.lang.Integer getEntryDepartment() {
		return getInt("entry_department");
	}

	public M setMajorDepartment(java.lang.Integer majorDepartment) {
		set("major_department", majorDepartment);
		return (M)this;
	}
	
	public java.lang.Integer getMajorDepartment() {
		return getInt("major_department");
	}

	public M setValue(java.lang.Integer value) {
		set("value", value);
		return (M)this;
	}
	
	public java.lang.Integer getValue() {
		return getInt("value");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

}
