package com.jyd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCusThirdpartCustomerCredit<M extends BaseCusThirdpartCustomerCredit<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setThirdpartQueryTypeId(java.lang.Integer thirdpartQueryTypeId) {
		set("thirdpart_query_type_id", thirdpartQueryTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getThirdpartQueryTypeId() {
		return getInt("thirdpart_query_type_id");
	}

	public M setIdCard(java.lang.String idCard) {
		set("id_card", idCard);
		return (M)this;
	}
	
	public java.lang.String getIdCard() {
		return getStr("id_card");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setQueryDate(java.util.Date queryDate) {
		set("query_date", queryDate);
		return (M)this;
	}
	
	public java.util.Date getQueryDate() {
		return get("query_date");
	}

	public M setHtmlsrc(java.lang.String htmlsrc) {
		set("htmlsrc", htmlsrc);
		return (M)this;
	}
	
	public java.lang.String getHtmlsrc() {
		return getStr("htmlsrc");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

}
