package com.jyd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysJob<M extends BaseSysJob<M>> extends Model<M> implements IBean {

	public M setJobId(java.lang.Integer jobId) {
		set("job_id", jobId);
		return (M)this;
	}
	
	public java.lang.Integer getJobId() {
		return getInt("job_id");
	}

}
