package com.jyd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCusCarAssess<M extends BaseCusCarAssess<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setLouver(java.lang.Integer louver) {
		set("louver", louver);
		return (M)this;
	}
	
	public java.lang.Integer getLouver() {
		return getInt("louver");
	}

	public M setSeat(java.lang.Integer seat) {
		set("seat", seat);
		return (M)this;
	}
	
	public java.lang.Integer getSeat() {
		return getInt("seat");
	}

	public M setLaunch(java.lang.Integer launch) {
		set("launch", launch);
		return (M)this;
	}
	
	public java.lang.Integer getLaunch() {
		return getInt("launch");
	}

	public M setPowertSeat(java.lang.Integer powertSeat) {
		set("powert_seat", powertSeat);
		return (M)this;
	}
	
	public java.lang.Integer getPowertSeat() {
		return getInt("powert_seat");
	}

	public M setPowerBoot(java.lang.Integer powerBoot) {
		set("power_boot", powerBoot);
		return (M)this;
	}
	
	public java.lang.Integer getPowerBoot() {
		return getInt("power_boot");
	}

	public M setSeatHeating(java.lang.Integer seatHeating) {
		set("seat_heating", seatHeating);
		return (M)this;
	}
	
	public java.lang.Integer getSeatHeating() {
		return getInt("seat_heating");
	}

	public M setGps(java.lang.Integer gps) {
		set("gps", gps);
		return (M)this;
	}
	
	public java.lang.Integer getGps() {
		return getInt("gps");
	}

	public M setElectronicSuspension(java.lang.Integer electronicSuspension) {
		set("electronic_suspension", electronicSuspension);
		return (M)this;
	}
	
	public java.lang.Integer getElectronicSuspension() {
		return getInt("electronic_suspension");
	}

	public M setLookedUpAndPrompt(java.lang.Integer lookedUpAndPrompt) {
		set("Looked_up_and_prompt", lookedUpAndPrompt);
		return (M)this;
	}
	
	public java.lang.Integer getLookedUpAndPrompt() {
		return getInt("Looked_up_and_prompt");
	}

	public M setSeatNum(java.lang.Integer seatNum) {
		set("seat_num", seatNum);
		return (M)this;
	}
	
	public java.lang.Integer getSeatNum() {
		return getInt("seat_num");
	}

	public M setCarAccessory(java.lang.String carAccessory) {
		set("car_accessory", carAccessory);
		return (M)this;
	}
	
	public java.lang.String getCarAccessory() {
		return getStr("car_accessory");
	}

	public M setCarVeer(java.lang.String carVeer) {
		set("car_veer", carVeer);
		return (M)this;
	}
	
	public java.lang.String getCarVeer() {
		return getStr("car_veer");
	}

	public M setEngine(java.lang.String engine) {
		set("engine", engine);
		return (M)this;
	}
	
	public java.lang.String getEngine() {
		return getStr("engine");
	}

	public M setSpeedchangingbox(java.lang.String speedchangingbox) {
		set("speedchangingbox", speedchangingbox);
		return (M)this;
	}
	
	public java.lang.String getSpeedchangingbox() {
		return getStr("speedchangingbox");
	}

	public M setAbsorber(java.lang.String absorber) {
		set("absorber", absorber);
		return (M)this;
	}
	
	public java.lang.String getAbsorber() {
		return getStr("absorber");
	}

	public M setExhaustpipe(java.lang.String exhaustpipe) {
		set("exhaustpipe", exhaustpipe);
		return (M)this;
	}
	
	public java.lang.String getExhaustpipe() {
		return getStr("exhaustpipe");
	}

	public M setAirConditioningEquipment(java.lang.String airConditioningEquipment) {
		set("air_conditioning_equipment", airConditioningEquipment);
		return (M)this;
	}
	
	public java.lang.String getAirConditioningEquipment() {
		return getStr("air_conditioning_equipment");
	}

	public M setCheckTheResult(java.lang.String checkTheResult) {
		set("check_the_result", checkTheResult);
		return (M)this;
	}
	
	public java.lang.String getCheckTheResult() {
		return getStr("check_the_result");
	}

	public M setCarCondition(java.lang.String carCondition) {
		set("car_condition", carCondition);
		return (M)this;
	}
	
	public java.lang.String getCarCondition() {
		return getStr("car_condition");
	}

	public M setFault(java.lang.String fault) {
		set("fault", fault);
		return (M)this;
	}
	
	public java.lang.String getFault() {
		return getStr("fault");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setCusContractId(java.lang.Integer cusContractId) {
		set("cus_contract_id", cusContractId);
		return (M)this;
	}
	
	public java.lang.Integer getCusContractId() {
		return getInt("cus_contract_id");
	}

}
