package com.jyd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWfFormGooutHomevisitV1<M extends BaseWfFormGooutHomevisitV1<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setGooutTheReason(java.lang.String gooutTheReason) {
		set("goout_the_reason", gooutTheReason);
		return (M)this;
	}
	
	public java.lang.String getGooutTheReason() {
		return getStr("goout_the_reason");
	}

	public M setGooutStartDate(java.util.Date gooutStartDate) {
		set("goout_start_date", gooutStartDate);
		return (M)this;
	}
	
	public java.util.Date getGooutStartDate() {
		return get("goout_start_date");
	}

	public M setGooutEndDate(java.util.Date gooutEndDate) {
		set("goout_end_date", gooutEndDate);
		return (M)this;
	}
	
	public java.util.Date getGooutEndDate() {
		return get("goout_end_date");
	}

	public M setPresentAddress(java.lang.String presentAddress) {
		set("present_address", presentAddress);
		return (M)this;
	}
	
	public java.lang.String getPresentAddress() {
		return getStr("present_address");
	}

	public M setPropertyAddress(java.lang.String propertyAddress) {
		set("property_address", propertyAddress);
		return (M)this;
	}
	
	public java.lang.String getPropertyAddress() {
		return getStr("property_address");
	}

	public M setPropertyStatus(java.lang.String propertyStatus) {
		set("property_status", propertyStatus);
		return (M)this;
	}
	
	public java.lang.String getPropertyStatus() {
		return getStr("property_status");
	}

	public M setManagetPhony(java.lang.String managetPhony) {
		set("managet_phony", managetPhony);
		return (M)this;
	}
	
	public java.lang.String getManagetPhony() {
		return getStr("managet_phony");
	}

	public M setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
		return (M)this;
	}
	
	public java.lang.String getCompanyName() {
		return getStr("company_name");
	}

	public M setCompanyAddress(java.lang.String companyAddress) {
		set("company_address", companyAddress);
		return (M)this;
	}
	
	public java.lang.String getCompanyAddress() {
		return getStr("company_address");
	}

	public M setCompanyManagerphony(java.lang.String companyManagerphony) {
		set("company_managerphony", companyManagerphony);
		return (M)this;
	}
	
	public java.lang.String getCompanyManagerphony() {
		return getStr("company_managerphony");
	}

	public M setCompanyStatus(java.lang.String companyStatus) {
		set("company_status", companyStatus);
		return (M)this;
	}
	
	public java.lang.String getCompanyStatus() {
		return getStr("company_status");
	}

	public M setComprehensiveEvaluation(java.lang.String comprehensiveEvaluation) {
		set("comprehensive_evaluation", comprehensiveEvaluation);
		return (M)this;
	}
	
	public java.lang.String getComprehensiveEvaluation() {
		return getStr("comprehensive_evaluation");
	}

	public M setAssessmentLevel(java.lang.String assessmentLevel) {
		set("assessment_level", assessmentLevel);
		return (M)this;
	}
	
	public java.lang.String getAssessmentLevel() {
		return getStr("assessment_level");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
