package com.jyd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCusContract<M extends BaseCusContract<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCusName(java.lang.String cusName) {
		set("cus_name", cusName);
		return (M)this;
	}
	
	public java.lang.String getCusName() {
		return getStr("cus_name");
	}

	public M setCusIdNo(java.lang.String cusIdNo) {
		set("cus_id_no", cusIdNo);
		return (M)this;
	}
	
	public java.lang.String getCusIdNo() {
		return getStr("cus_id_no");
	}

	public M setCusAddress(java.lang.String cusAddress) {
		set("cus_address", cusAddress);
		return (M)this;
	}
	
	public java.lang.String getCusAddress() {
		return getStr("cus_address");
	}

	public M setCusPhone(java.lang.String cusPhone) {
		set("cus_phone", cusPhone);
		return (M)this;
	}
	
	public java.lang.String getCusPhone() {
		return getStr("cus_phone");
	}

	public M setCusBankNo(java.lang.String cusBankNo) {
		set("cus_bank_no", cusBankNo);
		return (M)this;
	}
	
	public java.lang.String getCusBankNo() {
		return getStr("cus_bank_no");
	}

	public M setCusContractNo(java.lang.String cusContractNo) {
		set("cus_contract_no", cusContractNo);
		return (M)this;
	}
	
	public java.lang.String getCusContractNo() {
		return getStr("cus_contract_no");
	}

	public M setProductId(java.lang.Integer productId) {
		set("product_id", productId);
		return (M)this;
	}
	
	public java.lang.Integer getProductId() {
		return getInt("product_id");
	}

	public M setBorrowingPurpose(java.lang.String borrowingPurpose) {
		set("borrowing_purpose", borrowingPurpose);
		return (M)this;
	}
	
	public java.lang.String getBorrowingPurpose() {
		return getStr("borrowing_purpose");
	}

	public M setBorrowingAmount(java.lang.Double borrowingAmount) {
		set("borrowing_amount", borrowingAmount);
		return (M)this;
	}
	
	public java.lang.Double getBorrowingAmount() {
		return getDouble("borrowing_amount");
	}

	public M setRepaymentStageId(java.lang.Integer repaymentStageId) {
		set("repayment_stage_id", repaymentStageId);
		return (M)this;
	}
	
	public java.lang.Integer getRepaymentStageId() {
		return getInt("repayment_stage_id");
	}

	public M setContractVersionId(java.lang.Integer contractVersionId) {
		set("contract_version_id", contractVersionId);
		return (M)this;
	}
	
	public java.lang.Integer getContractVersionId() {
		return getInt("contract_version_id");
	}

	public M setPlate(java.lang.String plate) {
		set("plate", plate);
		return (M)this;
	}
	
	public java.lang.String getPlate() {
		return getStr("plate");
	}

	public M setEngineNo(java.lang.String engineNo) {
		set("engine_no", engineNo);
		return (M)this;
	}
	
	public java.lang.String getEngineNo() {
		return getStr("engine_no");
	}

	public M setVin(java.lang.String vin) {
		set("vin", vin);
		return (M)this;
	}
	
	public java.lang.String getVin() {
		return getStr("vin");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setStartDate(java.util.Date startDate) {
		set("start_date", startDate);
		return (M)this;
	}
	
	public java.util.Date getStartDate() {
		return get("start_date");
	}

	public M setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
		return (M)this;
	}
	
	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public M setVehicleModel(java.lang.String vehicleModel) {
		set("vehicle_model", vehicleModel);
		return (M)this;
	}
	
	public java.lang.String getVehicleModel() {
		return getStr("vehicle_model");
	}

	public M setCusPersonalInfoId(java.lang.Integer cusPersonalInfoId) {
		set("cus_personal_info_id", cusPersonalInfoId);
		return (M)this;
	}
	
	public java.lang.Integer getCusPersonalInfoId() {
		return getInt("cus_personal_info_id");
	}

	public M setRepaymentAccountId(java.lang.Integer repaymentAccountId) {
		set("repayment_account_id", repaymentAccountId);
		return (M)this;
	}
	
	public java.lang.Integer getRepaymentAccountId() {
		return getInt("repayment_account_id");
	}

	public M setMortgagor(java.lang.String mortgagor) {
		set("mortgagor", mortgagor);
		return (M)this;
	}
	
	public java.lang.String getMortgagor() {
		return getStr("mortgagor");
	}

	public M setRepaymentAccount(java.lang.String repaymentAccount) {
		set("repayment_account", repaymentAccount);
		return (M)this;
	}
	
	public java.lang.String getRepaymentAccount() {
		return getStr("repayment_account");
	}

	public M setBankName(java.lang.String bankName) {
		set("bank_name", bankName);
		return (M)this;
	}
	
	public java.lang.String getBankName() {
		return getStr("bank_name");
	}

	public M setBrand(java.lang.String brand) {
		set("brand", brand);
		return (M)this;
	}
	
	public java.lang.String getBrand() {
		return getStr("brand");
	}

	public M setMortgagorIdcard(java.lang.String mortgagorIdcard) {
		set("mortgagor_idcard", mortgagorIdcard);
		return (M)this;
	}
	
	public java.lang.String getMortgagorIdcard() {
		return getStr("mortgagor_idcard");
	}

	public M setMortgagorAdress(java.lang.String mortgagorAdress) {
		set("mortgagor_adress", mortgagorAdress);
		return (M)this;
	}
	
	public java.lang.String getMortgagorAdress() {
		return getStr("mortgagor_adress");
	}

	public M setRepaymentBankName(java.lang.String repaymentBankName) {
		set("repayment_bank_name", repaymentBankName);
		return (M)this;
	}
	
	public java.lang.String getRepaymentBankName() {
		return getStr("repayment_bank_name");
	}

	public M setMortgagerId(java.lang.Integer mortgagerId) {
		set("mortgager_id", mortgagerId);
		return (M)this;
	}
	
	public java.lang.Integer getMortgagerId() {
		return getInt("mortgager_id");
	}

	public M setRepaymentName(java.lang.String repaymentName) {
		set("repayment_name", repaymentName);
		return (M)this;
	}
	
	public java.lang.String getRepaymentName() {
		return getStr("repayment_name");
	}

	public M setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
		return (M)this;
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public M setVehiclerinfoId(java.lang.Integer vehiclerinfoId) {
		set("vehiclerinfo_id", vehiclerinfoId);
		return (M)this;
	}
	
	public java.lang.Integer getVehiclerinfoId() {
		return getInt("vehiclerinfo_id");
	}

	public M setCarValuation(java.lang.Double carValuation) {
		set("car_valuation", carValuation);
		return (M)this;
	}
	
	public java.lang.Double getCarValuation() {
		return getDouble("car_valuation");
	}

	public M setPurchasePrice(java.lang.Double purchasePrice) {
		set("purchase_price", purchasePrice);
		return (M)this;
	}
	
	public java.lang.Double getPurchasePrice() {
		return getDouble("purchase_price");
	}

	public M setPrincipal(java.lang.Double principal) {
		set("principal", principal);
		return (M)this;
	}
	
	public java.lang.Double getPrincipal() {
		return getDouble("principal");
	}

	public M setLateFee(java.lang.Double lateFee) {
		set("late_fee", lateFee);
		return (M)this;
	}
	
	public java.lang.Double getLateFee() {
		return getDouble("late_fee");
	}

	public M setExpLoanAmonut(java.math.BigDecimal expLoanAmonut) {
		set("exp_loan_amonut", expLoanAmonut);
		return (M)this;
	}
	
	public java.math.BigDecimal getExpLoanAmonut() {
		return get("exp_loan_amonut");
	}

	public M setEmployeeId(java.lang.Integer employeeId) {
		set("employee_id", employeeId);
		return (M)this;
	}
	
	public java.lang.Integer getEmployeeId() {
		return getInt("employee_id");
	}

	public M setPersonResponsibleId(java.lang.Integer personResponsibleId) {
		set("person_responsible_id", personResponsibleId);
		return (M)this;
	}
	
	public java.lang.Integer getPersonResponsibleId() {
		return getInt("person_responsible_id");
	}

	public M setSettlementDate(java.util.Date settlementDate) {
		set("settlement_date", settlementDate);
		return (M)this;
	}
	
	public java.util.Date getSettlementDate() {
		return get("settlement_date");
	}

	public M setAssetsTypeId(java.lang.Integer assetsTypeId) {
		set("assets_type_id", assetsTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getAssetsTypeId() {
		return getInt("assets_type_id");
	}

	public M setBusinessSourceId(java.lang.Integer businessSourceId) {
		set("business_source_id", businessSourceId);
		return (M)this;
	}
	
	public java.lang.Integer getBusinessSourceId() {
		return getInt("business_source_id");
	}

	public M setOverdueDays(java.lang.Integer overdueDays) {
		set("overdue_days", overdueDays);
		return (M)this;
	}
	
	public java.lang.Integer getOverdueDays() {
		return getInt("overdue_days");
	}

	public M setMentionPay(java.lang.Double mentionPay) {
		set("mentionPay", mentionPay);
		return (M)this;
	}
	
	public java.lang.Double getMentionPay() {
		return getDouble("mentionPay");
	}

	public M setSellerDefaultDate(java.util.Date sellerDefaultDate) {
		set("seller_default_date", sellerDefaultDate);
		return (M)this;
	}
	
	public java.util.Date getSellerDefaultDate() {
		return get("seller_default_date");
	}

	public M setTrailCarDate(java.util.Date trailCarDate) {
		set("trail_car_date", trailCarDate);
		return (M)this;
	}
	
	public java.util.Date getTrailCarDate() {
		return get("trail_car_date");
	}

	public M setSellCarDate(java.util.Date sellCarDate) {
		set("sell_car_date", sellCarDate);
		return (M)this;
	}
	
	public java.util.Date getSellCarDate() {
		return get("sell_car_date");
	}

	public M setSellCarAmount(java.lang.Double sellCarAmount) {
		set("sell_car_amount", sellCarAmount);
		return (M)this;
	}
	
	public java.lang.Double getSellCarAmount() {
		return getDouble("sell_car_amount");
	}

	public M setCollectPrincipal(java.lang.Double collectPrincipal) {
		set("collect_principal", collectPrincipal);
		return (M)this;
	}
	
	public java.lang.Double getCollectPrincipal() {
		return getDouble("collect_principal");
	}

	public M setCollectInterest(java.lang.Double collectInterest) {
		set("collect_interest", collectInterest);
		return (M)this;
	}
	
	public java.lang.Double getCollectInterest() {
		return getDouble("collect_interest");
	}

	public M setCollectLatefee(java.lang.Double collectLatefee) {
		set("collect_latefee", collectLatefee);
		return (M)this;
	}
	
	public java.lang.Double getCollectLatefee() {
		return getDouble("collect_latefee");
	}

	public M setHasflagPrincipal(java.lang.Double hasflagPrincipal) {
		set("hasFlag_principal", hasflagPrincipal);
		return (M)this;
	}
	
	public java.lang.Double getHasflagPrincipal() {
		return getDouble("hasFlag_principal");
	}

	public M setHasflagInterest(java.lang.Double hasflagInterest) {
		set("hasFlag_interest", hasflagInterest);
		return (M)this;
	}
	
	public java.lang.Double getHasflagInterest() {
		return getDouble("hasFlag_interest");
	}

	public M setHasflagLatafee(java.lang.Double hasflagLatafee) {
		set("hasFlag_latafee", hasflagLatafee);
		return (M)this;
	}
	
	public java.lang.Double getHasflagLatafee() {
		return getDouble("hasFlag_latafee");
	}

	public M setPurchaseDate(java.util.Date purchaseDate) {
		set("purchase_date", purchaseDate);
		return (M)this;
	}
	
	public java.util.Date getPurchaseDate() {
		return get("purchase_date");
	}

	public M setContractManageTypeId(java.lang.Integer contractManageTypeId) {
		set("contract_manage_type_id", contractManageTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getContractManageTypeId() {
		return getInt("contract_manage_type_id");
	}

	public M setContractManageValue(java.lang.Double contractManageValue) {
		set("contract_manage_value", contractManageValue);
		return (M)this;
	}
	
	public java.lang.Double getContractManageValue() {
		return getDouble("contract_manage_value");
	}

	public M setBidAmount(java.lang.Double bidAmount) {
		set("bid_amount", bidAmount);
		return (M)this;
	}
	
	public java.lang.Double getBidAmount() {
		return getDouble("bid_amount");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setSurplusCapital(java.lang.Double surplusCapital) {
		set("surplus_capital", surplusCapital);
		return (M)this;
	}
	
	public java.lang.Double getSurplusCapital() {
		return getDouble("surplus_capital");
	}

	public M setSurplusInterest(java.lang.Double surplusInterest) {
		set("surplus_interest", surplusInterest);
		return (M)this;
	}
	
	public java.lang.Double getSurplusInterest() {
		return getDouble("surplus_interest");
	}

	public M setSurplusOtherFee(java.lang.Double surplusOtherFee) {
		set("surplus_other_fee", surplusOtherFee);
		return (M)this;
	}
	
	public java.lang.Double getSurplusOtherFee() {
		return getDouble("surplus_other_fee");
	}

	public M setReturnPointNum(java.lang.Double returnPointNum) {
		set("return_point_num", returnPointNum);
		return (M)this;
	}
	
	public java.lang.Double getReturnPointNum() {
		return getDouble("return_point_num");
	}

	public M setBaRepaymentTypeId(java.lang.Integer baRepaymentTypeId) {
		set("ba_repayment_type_id", baRepaymentTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getBaRepaymentTypeId() {
		return getInt("ba_repayment_type_id");
	}

	public M setBaCalcStageVersionId(java.lang.Integer baCalcStageVersionId) {
		set("ba_calc_stage_version_id", baCalcStageVersionId);
		return (M)this;
	}
	
	public java.lang.Integer getBaCalcStageVersionId() {
		return getInt("ba_calc_stage_version_id");
	}

	public M setRealLoanDate(java.util.Date realLoanDate) {
		set("real_loan_date", realLoanDate);
		return (M)this;
	}
	
	public java.util.Date getRealLoanDate() {
		return get("real_loan_date");
	}

	public M setRenewal(java.lang.Integer renewal) {
		set("renewal", renewal);
		return (M)this;
	}
	
	public java.lang.Integer getRenewal() {
		return getInt("renewal");
	}

	public M setRealLoanEndDate(java.util.Date realLoanEndDate) {
		set("real_loan_end_date", realLoanEndDate);
		return (M)this;
	}
	
	public java.util.Date getRealLoanEndDate() {
		return get("real_loan_end_date");
	}

	public M setBaProductTypeId(java.lang.Integer baProductTypeId) {
		set("ba_product_type_id", baProductTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getBaProductTypeId() {
		return getInt("ba_product_type_id");
	}

	public M setProductType(java.lang.String productType) {
		set("product_type", productType);
		return (M)this;
	}
	
	public java.lang.String getProductType() {
		return getStr("product_type");
	}

	public M setFeeStage(java.lang.Integer feeStage) {
		set("fee_stage", feeStage);
		return (M)this;
	}
	
	public java.lang.Integer getFeeStage() {
		return getInt("fee_stage");
	}

	public M setBaProductClassifyId(java.lang.Integer baProductClassifyId) {
		set("ba_product_classify_id", baProductClassifyId);
		return (M)this;
	}
	
	public java.lang.Integer getBaProductClassifyId() {
		return getInt("ba_product_classify_id");
	}

	public M setBaSettlementTypeId(java.lang.Integer baSettlementTypeId) {
		set("ba_settlement_type_id", baSettlementTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getBaSettlementTypeId() {
		return getInt("ba_settlement_type_id");
	}

	public M setFollowEmployeeId(java.lang.Integer followEmployeeId) {
		set("follow_employee_id", followEmployeeId);
		return (M)this;
	}
	
	public java.lang.Integer getFollowEmployeeId() {
		return getInt("follow_employee_id");
	}

}
