package com.jyd.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWfWorkFlow<M extends BaseWfWorkFlow<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setWorkFlowTypeId(java.lang.Integer workFlowTypeId) {
		set("work_flow_type_id", workFlowTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getWorkFlowTypeId() {
		return getInt("work_flow_type_id");
	}

	public M setMessage(java.lang.String message) {
		set("message", message);
		return (M)this;
	}
	
	public java.lang.String getMessage() {
		return getStr("message");
	}

	public M setBeginTime(java.util.Date beginTime) {
		set("begin_time", beginTime);
		return (M)this;
	}
	
	public java.util.Date getBeginTime() {
		return get("begin_time");
	}

	public M setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
		return (M)this;
	}
	
	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
		return (M)this;
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

}
