package com.jyd.common.model;

import com.jyd.common.model.base.BaseAttDailyAttend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AttDailyAttend extends BaseAttDailyAttend<AttDailyAttend> {
	
}
