package com.jyd.common.model;

import com.jyd.common.model.base.BaseAttEmpDate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AttEmpDate extends BaseAttEmpDate<AttEmpDate> {
	
}
