package com.jyd.common.model;

import com.jyd.common.model.base.BaseAttEvectionType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AttEvectionType extends BaseAttEvectionType<AttEvectionType> {
	
}
