package com.jyd.common.model;

import com.jyd.common.model.base.BaseAttEmpMonth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AttEmpMonth extends BaseAttEmpMonth<AttEmpMonth> {
	
}
