package com.jyd.common.model;

import com.jyd.common.model.base.BaseAttEvection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AttEvection extends BaseAttEvection<AttEvection> {
	
}
