package com.jyd.common.model;

import com.jyd.common.model.base.BaseAttLeaveType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AttLeaveType extends BaseAttLeaveType<AttLeaveType> {
	
}
