package com.jyd.common.model;

import com.jyd.common.model.base.BaseAttMonthlyAttend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AttMonthlyAttend extends BaseAttMonthlyAttend<AttMonthlyAttend> {
	
}
