package com.jyd.common.model;

import com.jyd.common.model.base.BaseAttOvertimeType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AttOvertimeType extends BaseAttOvertimeType<AttOvertimeType> {
	
}
