package com.jyd.common.model;

import com.jyd.common.model.base.BaseAttOvertime;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AttOvertime extends BaseAttOvertime<AttOvertime> {
	
}
