package com.jyd.common.model;

import com.jyd.common.model.base.BaseAttRestTime;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AttRestTime extends BaseAttRestTime<AttRestTime> {
	
}
