package com.jyd.common.model;

import com.jyd.common.model.base.BaseAttScheduling;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AttScheduling extends BaseAttScheduling<AttScheduling> {
	
}
