package com.jyd.common.model;

import com.jyd.common.model.base.BaseAttShiftWorktime;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AttShiftWorktime extends BaseAttShiftWorktime<AttShiftWorktime> {
	
}
