package com.jyd.common.model;

import com.jyd.common.model.base.BaseAttWorkTime;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AttWorkTime extends BaseAttWorkTime<AttWorkTime> {
	
}
