package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaAssetsType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaAssetsType extends BaseBaAssetsType<BaAssetsType> {
	
}
