package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaBusinessSource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaBusinessSource extends BaseBaBusinessSource<BaBusinessSource> {
	
}
