package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaCalcStageVersion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaCalcStageVersion extends BaseBaCalcStageVersion<BaCalcStageVersion> {
	
}
