package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaCostType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaCostType extends BaseBaCostType<BaCostType> {
	
}
