package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaContractVersion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaContractVersion extends BaseBaContractVersion<BaContractVersion> {
	
}
