package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaContractManageType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaContractManageType extends BaseBaContractManageType<BaContractManageType> {
	
}
