package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaDepartmentType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaDepartmentType extends BaseBaDepartmentType<BaDepartmentType> {
	
}
