package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaDutyType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaDutyType extends BaseBaDutyType<BaDutyType> {
	
}
