package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaEducationType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaEducationType extends BaseBaEducationType<BaEducationType> {
	
}
