package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaEmployeeProperties;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaEmployeeProperties extends BaseBaEmployeeProperties<BaEmployeeProperties> {
	
}
