package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaGpsCostType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaGpsCostType extends BaseBaGpsCostType<BaGpsCostType> {
	
}
