package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaInsuranceType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaInsuranceType extends BaseBaInsuranceType<BaInsuranceType> {
	
}
