package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaLoanType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaLoanType extends BaseBaLoanType<BaLoanType> {
	
}
