package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaMortgager;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaMortgager extends BaseBaMortgager<BaMortgager> {
	
}
