package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaParkingFee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaParkingFee extends BaseBaParkingFee<BaParkingFee> {
	
}
