package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaPositionType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaPositionType extends BaseBaPositionType<BaPositionType> {
	
}
