package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaPropertyType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaPropertyType extends BaseBaPropertyType<BaPropertyType> {
	
}
