package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaProductCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaProductCategory extends BaseBaProductCategory<BaProductCategory> {
	
}
