package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaProductParameter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaProductParameter extends BaseBaProductParameter<BaProductParameter> {
	
}
