package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaProductType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaProductType extends BaseBaProductType<BaProductType> {
	
}
