package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaProcessType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaProcessType extends BaseBaProcessType<BaProcessType> {
	
}
