package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaProductClassify;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaProductClassify extends BaseBaProductClassify<BaProductClassify> {
	
}
