package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaRepaymentStage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaRepaymentStage extends BaseBaRepaymentStage<BaRepaymentStage> {
	
}
