package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaRepaymentType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaRepaymentType extends BaseBaRepaymentType<BaRepaymentType> {
	
}
