package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaRepaymentAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaRepaymentAccount extends BaseBaRepaymentAccount<BaRepaymentAccount> {
	
}
