package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaSalaryLevel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaSalaryLevel extends BaseBaSalaryLevel<BaSalaryLevel> {
	
}
