package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaScheduleType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaScheduleType extends BaseBaScheduleType<BaScheduleType> {
	
}
