package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaSettlementType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaSettlementType extends BaseBaSettlementType<BaSettlementType> {
	
}
