package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaStore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaStore extends BaseBaStore<BaStore> {
	public static final BaStore dao = new BaStore();
}
