package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaThirdpartCompany;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaThirdpartCompany extends BaseBaThirdpartCompany<BaThirdpartCompany> {
	
}
