package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaThirdpartQueryType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaThirdpartQueryType extends BaseBaThirdpartQueryType<BaThirdpartQueryType> {
	
}
