package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaUploadFileType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaUploadFileType extends BaseBaUploadFileType<BaUploadFileType> {
	
}
