package com.jyd.common.model;

import com.jyd.common.model.base.BaseBaVehicleType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaVehicleType extends BaseBaVehicleType<BaVehicleType> {
	
}
