package com.jyd.common.model;

import com.jyd.common.model.base.BaseContractFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ContractFile extends BaseContractFile<ContractFile> {
	
}
