package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusBorrower;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusBorrower extends BaseCusBorrower<CusBorrower> {
	
}
