package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusBorrowerCreditInformationTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusBorrowerCreditInformationTable extends BaseCusBorrowerCreditInformationTable<CusBorrowerCreditInformationTable> {
	
}
