package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusContractStageFee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusContractStageFee extends BaseCusContractStageFee<CusContractStageFee> {
	
}
