package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusContractPrintFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusContractPrintFile extends BaseCusContractPrintFile<CusContractPrintFile> {
	
}
