package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusContractCost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusContractCost extends BaseCusContractCost<CusContractCost> {
	
}
