package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusContractGpsLateFee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusContractGpsLateFee extends BaseCusContractGpsLateFee<CusContractGpsLateFee> {
	
}
