package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusContractLateFee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusContractLateFee extends BaseCusContractLateFee<CusContractLateFee> {
	
}
