package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusContractLender;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusContractLender extends BaseCusContractLender<CusContractLender> {
	
}
