package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusContractFollowEmployeeHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusContractFollowEmployeeHistory extends BaseCusContractFollowEmployeeHistory<CusContractFollowEmployeeHistory> {
	
}
