package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusContractMonthDetailed;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusContractMonthDetailed extends BaseCusContractMonthDetailed<CusContractMonthDetailed> {
	
}
