package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusContractUploadfile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusContractUploadfile extends BaseCusContractUploadfile<CusContractUploadfile> {
	
}
