package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusContractRenewal;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusContractRenewal extends BaseCusContractRenewal<CusContractRenewal> {
	
}
