package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusContractStageFeeRepayment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusContractStageFeeRepayment extends BaseCusContractStageFeeRepayment<CusContractStageFeeRepayment> {
	
}
