package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusCarAssess;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusCarAssess extends BaseCusCarAssess<CusCarAssess> {
	
}
