package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusContractMonth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusContractMonth extends BaseCusContractMonth<CusContractMonth> {
	
}
