package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusContractBlacklist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusContractBlacklist extends BaseCusContractBlacklist<CusContractBlacklist> {
	
}
