package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusContractRepaymentOtherFee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusContractRepaymentOtherFee extends BaseCusContractRepaymentOtherFee<CusContractRepaymentOtherFee> {
	
}
