package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusContractRepayment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusContractRepayment extends BaseCusContractRepayment<CusContractRepayment> {
	
}
