package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusContractOverdueAmount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusContractOverdueAmount extends BaseCusContractOverdueAmount<CusContractOverdueAmount> {
	
}
