package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusContractStage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusContractStage extends BaseCusContractStage<CusContractStage> {
	
}
