package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusContractFaceTrialV1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusContractFaceTrialV1 extends BaseCusContractFaceTrialV1<CusContractFaceTrialV1> {
	
}
