package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusContractScheduleTrack;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusContractScheduleTrack extends BaseCusContractScheduleTrack<CusContractScheduleTrack> {
	
}
