package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusContractFaceTrial;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusContractFaceTrial extends BaseCusContractFaceTrial<CusContractFaceTrial> {
	
}
