package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusContract;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusContract extends BaseCusContract<CusContract> {
	public static final CusContract dao = new CusContract();
	
}
