package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusContractPara;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusContractPara extends BaseCusContractPara<CusContractPara> {
	
}
