package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusEquipment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusEquipment extends BaseCusEquipment<CusEquipment> {
	
}
