package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusGooutHomevisit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusGooutHomevisit extends BaseCusGooutHomevisit<CusGooutHomevisit> {
	
}
