package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusGpsinstall;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusGpsinstall extends BaseCusGpsinstall<CusGpsinstall> {
	
}
