package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusPersonalInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusPersonalInfo extends BaseCusPersonalInfo<CusPersonalInfo> {
	
}
