package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusSecondaryContactInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusSecondaryContactInfo extends BaseCusSecondaryContactInfo<CusSecondaryContactInfo> {
	
}
