package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusThirdpartQueryLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusThirdpartQueryLog extends BaseCusThirdpartQueryLog<CusThirdpartQueryLog> {
	
}
