package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusThirdpartTongdunQueryLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusThirdpartTongdunQueryLog extends BaseCusThirdpartTongdunQueryLog<CusThirdpartTongdunQueryLog> {
	
}
