package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusThirdpartCustomerCredit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusThirdpartCustomerCredit extends BaseCusThirdpartCustomerCredit<CusThirdpartCustomerCredit> {
	
}
