package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusThirdpartGpsVehicleBaseData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusThirdpartGpsVehicleBaseData extends BaseCusThirdpartGpsVehicleBaseData<CusThirdpartGpsVehicleBaseData> {
	
}
