package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusThirdpartTongdunCustomerCredit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusThirdpartTongdunCustomerCredit extends BaseCusThirdpartTongdunCustomerCredit<CusThirdpartTongdunCustomerCredit> {
	
}
