package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusThirdpartBairongCustomerCredit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusThirdpartBairongCustomerCredit extends BaseCusThirdpartBairongCustomerCredit<CusThirdpartBairongCustomerCredit> {
	
}
