package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusThirdpartTongdunQueryType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusThirdpartTongdunQueryType extends BaseCusThirdpartTongdunQueryType<CusThirdpartTongdunQueryType> {
	
}
