package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusThirdpartBairongQueryType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusThirdpartBairongQueryType extends BaseCusThirdpartBairongQueryType<CusThirdpartBairongQueryType> {
	
}
