package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusThirdpartBairongQueryLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusThirdpartBairongQueryLog extends BaseCusThirdpartBairongQueryLog<CusThirdpartBairongQueryLog> {
	
}
