package com.jyd.common.model;

import com.jyd.common.model.base.BaseCusVehicleInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CusVehicleInfo extends BaseCusVehicleInfo<CusVehicleInfo> {
	
}
