package com.jyd.common.model;

import com.jyd.common.model.base.BaseEmployeeSalaryItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmployeeSalaryItem extends BaseEmployeeSalaryItem<EmployeeSalaryItem> {
	
}
