package com.jyd.common.model;

import com.jyd.common.model.base.BaseFundContractCost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FundContractCost extends BaseFundContractCost<FundContractCost> {
	
}
