package com.jyd.common.model;

import com.jyd.common.model.base.BaseFundProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FundProduct extends BaseFundProduct<FundProduct> {
	
}
