package com.jyd.common.model;

import com.jyd.common.model.base.BaseFundContractStageFee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FundContractStageFee extends BaseFundContractStageFee<FundContractStageFee> {
	
}
