package com.jyd.common.model;

import com.jyd.common.model.base.BaseFundContractStage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FundContractStage extends BaseFundContractStage<FundContractStage> {
	
}
