package com.jyd.common.model;

import com.jyd.common.model.base.BaseFundContractStageRepayment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FundContractStageRepayment extends BaseFundContractStageRepayment<FundContractStageRepayment> {
	
}
