package com.jyd.common.model;

import com.jyd.common.model.base.BaseFundProductPara;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FundProductPara extends BaseFundProductPara<FundProductPara> {
	
}
