package com.jyd.common.model;

import com.jyd.common.model.base.BaseFundContract;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FundContract extends BaseFundContract<FundContract> {
	
}
