package com.jyd.common.model;

import com.jyd.common.model.base.BaseHbaseMapType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HbaseMapType extends BaseHbaseMapType<HbaseMapType> {
	
}
