package com.jyd.common.model;

import com.jyd.common.model.base.BaseHrContract;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrContract extends BaseHrContract<HrContract> {
	
}
