package com.jyd.common.model;

import com.jyd.common.model.base.BaseHrDepartmentWeeklyStatement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrDepartmentWeeklyStatement extends BaseHrDepartmentWeeklyStatement<HrDepartmentWeeklyStatement> {
	
}
