package com.jyd.common.model;

import com.jyd.common.model.base.BaseHrDepartment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrDepartment extends BaseHrDepartment<HrDepartment> {
	
}
