package com.jyd.common.model;

import com.jyd.common.model.base.BaseHrDepartmentMonthlyStatement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrDepartmentMonthlyStatement extends BaseHrDepartmentMonthlyStatement<HrDepartmentMonthlyStatement> {
	
}
