package com.jyd.common.model;

import com.jyd.common.model.base.BaseHrEmployee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrEmployee extends BaseHrEmployee<HrEmployee> {
	
}
