package com.jyd.common.model;

import com.jyd.common.model.base.BaseHrEmpExperience;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrEmpExperience extends BaseHrEmpExperience<HrEmpExperience> {
	
}
