package com.jyd.common.model;

import com.jyd.common.model.base.BaseHrEmpDuty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrEmpDuty extends BaseHrEmpDuty<HrEmpDuty> {
	
}
