package com.jyd.common.model;

import com.jyd.common.model.base.BaseHrEmergenceContact;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrEmergenceContact extends BaseHrEmergenceContact<HrEmergenceContact> {
	
}
