package com.jyd.common.model;

import com.jyd.common.model.base.BaseHrParentDepartment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrParentDepartment extends BaseHrParentDepartment<HrParentDepartment> {
	
}
