package com.jyd.common.model;

import com.jyd.common.model.base.BaseHrSecondee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrSecondee extends BaseHrSecondee<HrSecondee> {
	
}
