package com.jyd.common.model;

import com.jyd.common.model.base.BaseHrSonDepartment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrSonDepartment extends BaseHrSonDepartment<HrSonDepartment> {
	
}
