package com.jyd.common.model;

import com.jyd.common.model.base.BaseHrWorkExperience;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HrWorkExperience extends BaseHrWorkExperience<HrWorkExperience> {
	
}
