package com.jyd.common.model;

import com.jyd.common.model.base.BaseMessageData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MessageData extends BaseMessageData<MessageData> {
	
}
