package com.jyd.common.model;

import com.jyd.common.model.base.BaseMessageType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MessageType extends BaseMessageType<MessageType> {
	
}
