package com.jyd.common.model;

import com.jyd.common.model.base.BaseProBusinessSource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProBusinessSource extends BaseProBusinessSource<ProBusinessSource> {
	
}
