package com.jyd.common.model;

import com.jyd.common.model.base.BaseProParameter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProParameter extends BaseProParameter<ProParameter> {
	
}
