package com.jyd.common.model;

import com.jyd.common.model.base.BaseProRepaymentStage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProRepaymentStage extends BaseProRepaymentStage<ProRepaymentStage> {
	
}
