package com.jyd.common.model;

import com.jyd.common.model.base.BaseProUploadFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProUploadFile extends BaseProUploadFile<ProUploadFile> {
	
}
