package com.jyd.common.model;

import com.jyd.common.model.base.BaseSalBaseSalaryItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SalBaseSalaryItem extends BaseSalBaseSalaryItem<SalBaseSalaryItem> {
	
}
