package com.jyd.common.model;

import com.jyd.common.model.base.BaseSalEmployeeSalary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SalEmployeeSalary extends BaseSalEmployeeSalary<SalEmployeeSalary> {
	
}
