package com.jyd.common.model;

import com.jyd.common.model.base.BaseSalEmployeeBaseSalary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SalEmployeeBaseSalary extends BaseSalEmployeeBaseSalary<SalEmployeeBaseSalary> {
	
}
