package com.jyd.common.model;

import com.jyd.common.model.base.BaseSalEmployeeSalaryHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SalEmployeeSalaryHistory extends BaseSalEmployeeSalaryHistory<SalEmployeeSalaryHistory> {
	
}
