package com.jyd.common.model;

import com.jyd.common.model.base.BaseSalEmployeeBaseSalaryHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SalEmployeeBaseSalaryHistory extends BaseSalEmployeeBaseSalaryHistory<SalEmployeeBaseSalaryHistory> {
	
}
