package com.jyd.common.model;

import com.jyd.common.model.base.BaseSalInsurance;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SalInsurance extends BaseSalInsurance<SalInsurance> {
	
}
