package com.jyd.common.model;

import com.jyd.common.model.base.BaseSalLockMonthSalary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SalLockMonthSalary extends BaseSalLockMonthSalary<SalLockMonthSalary> {
	
}
