package com.jyd.common.model;

import com.jyd.common.model.base.BaseSalMonthSalary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SalMonthSalary extends BaseSalMonthSalary<SalMonthSalary> {
	
}
