package com.jyd.common.model;

import com.jyd.common.model.base.BaseSalMonthSalaryExpand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SalMonthSalaryExpand extends BaseSalMonthSalaryExpand<SalMonthSalaryExpand> {
	
}
