package com.jyd.common.model;

import com.jyd.common.model.base.BaseSalSalaryStructure;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SalSalaryStructure extends BaseSalSalaryStructure<SalSalaryStructure> {
	
}
