package com.jyd.common.model;

import com.jyd.common.model.base.BaseSalSalaryItemType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SalSalaryItemType extends BaseSalSalaryItemType<SalSalaryItemType> {
	
}
