package com.jyd.common.model;

import com.jyd.common.model.base.BaseSalSalaryStructureBaseSalaryItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SalSalaryStructureBaseSalaryItem extends BaseSalSalaryStructureBaseSalaryItem<SalSalaryStructureBaseSalaryItem> {
	
}
