package com.jyd.common.model;

import com.jyd.common.model.base.BaseSalSalaryItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SalSalaryItem extends BaseSalSalaryItem<SalSalaryItem> {
	
}
