package com.jyd.common.model;

import com.jyd.common.model.base.BaseSchPeriodic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SchPeriodic extends BaseSchPeriodic<SchPeriodic> {
	
}
