package com.jyd.common.model;

import com.jyd.common.model.base.BaseSchTaskLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SchTaskLog extends BaseSchTaskLog<SchTaskLog> {
	
}
