package com.jyd.common.model;

import com.jyd.common.model.base.BaseStoLender;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StoLender extends BaseStoLender<StoLender> {
	
}
