package com.jyd.common.model;

import com.jyd.common.model.base.BaseStoMortgager;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StoMortgager extends BaseStoMortgager<StoMortgager> {
	
}
