package com.jyd.common.model;

import com.jyd.common.model.base.BaseStoRepaymentAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StoRepaymentAccount extends BaseStoRepaymentAccount<StoRepaymentAccount> {
	
}
