package com.jyd.common.model;

import com.jyd.common.model.base.BaseSysErrorLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysErrorLog extends BaseSysErrorLog<SysErrorLog> {
	
}
