package com.jyd.common.model;

import com.jyd.common.model.base.BaseSysGroupMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysGroupMenu extends BaseSysGroupMenu<SysGroupMenu> {
	
}
