package com.jyd.common.model;

import com.jyd.common.model.base.BaseSysGroupUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysGroupUser extends BaseSysGroupUser<SysGroupUser> {
	
}
