package com.jyd.common.model;

import com.jyd.common.model.base.BaseSysPageUseLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysPageUseLog extends BaseSysPageUseLog<SysPageUseLog> {
	
}
