package com.jyd.common.model;

import com.jyd.common.model.base.BaseSysUserMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserMenu extends BaseSysUserMenu<SysUserMenu> {
	
}
