package com.jyd.common.model;

import com.jyd.common.model.base.BaseTempCusThirdpartQueryLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TempCusThirdpartQueryLog extends BaseTempCusThirdpartQueryLog<TempCusThirdpartQueryLog> {
	
}
