package com.jyd.common.model;

import com.jyd.common.model.base.BaseTempCusThirdpartCustomerCredit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TempCusThirdpartCustomerCredit extends BaseTempCusThirdpartCustomerCredit<TempCusThirdpartCustomerCredit> {
	
}
