package com.jyd.common.model;

import com.jyd.common.model.base.BaseTestBatchInsert;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestBatchInsert extends BaseTestBatchInsert<TestBatchInsert> {
	
}
