package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormEmployeeContactV1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormEmployeeContactV1 extends BaseWfFormEmployeeContactV1<WfFormEmployeeContactV1> {
	
}
