package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormContractFaceTrialV3;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormContractFaceTrialV3 extends BaseWfFormContractFaceTrialV3<WfFormContractFaceTrialV3> {
	
}
