package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormLeaveEmployeeV1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormLeaveEmployeeV1 extends BaseWfFormLeaveEmployeeV1<WfFormLeaveEmployeeV1> {
	
}
