package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormGpsInstallV1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormGpsInstallV1 extends BaseWfFormGpsInstallV1<WfFormGpsInstallV1> {
	
}
