package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormAssemblyV1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormAssemblyV1 extends BaseWfFormAssemblyV1<WfFormAssemblyV1> {
	
}
