package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormEmployeePositionV1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormEmployeePositionV1 extends BaseWfFormEmployeePositionV1<WfFormEmployeePositionV1> {
	
}
