package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormEmployeeContractV1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormEmployeeContractV1 extends BaseWfFormEmployeeContractV1<WfFormEmployeeContractV1> {
	
}
