package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormCusContractUploadfile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormCusContractUploadfile extends BaseWfFormCusContractUploadfile<WfFormCusContractUploadfile> {
	
}
