package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormCusBorrower;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormCusBorrower extends BaseWfFormCusBorrower<WfFormCusBorrower> {
	
}
