package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormCusCarAssess;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormCusCarAssess extends BaseWfFormCusCarAssess<WfFormCusCarAssess> {
	
}
