package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormEmployeeDutyV1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormEmployeeDutyV1 extends BaseWfFormEmployeeDutyV1<WfFormEmployeeDutyV1> {
	
}
