package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormCusContractCost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormCusContractCost extends BaseWfFormCusContractCost<WfFormCusContractCost> {
	
}
