package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormCusContractLender;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormCusContractLender extends BaseWfFormCusContractLender<WfFormCusContractLender> {
	
}
