package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormSetSalaryV1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormSetSalaryV1 extends BaseWfFormSetSalaryV1<WfFormSetSalaryV1> {
	
}
