package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormEmployeeSalaryV1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormEmployeeSalaryV1 extends BaseWfFormEmployeeSalaryV1<WfFormEmployeeSalaryV1> {
	
}
