package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormCusContractPara;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormCusContractPara extends BaseWfFormCusContractPara<WfFormCusContractPara> {
	
}
