package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormFormalApplyV1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormFormalApplyV1 extends BaseWfFormFormalApplyV1<WfFormFormalApplyV1> {
	
}
