package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormAdjustSalaryV1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormAdjustSalaryV1 extends BaseWfFormAdjustSalaryV1<WfFormAdjustSalaryV1> {
	
}
