package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormPersonalInfoV2;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormPersonalInfoV2 extends BaseWfFormPersonalInfoV2<WfFormPersonalInfoV2> {
	
}
