package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormCusEquipment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormCusEquipment extends BaseWfFormCusEquipment<WfFormCusEquipment> {
	
}
