package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormRecordPerson;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormRecordPerson extends BaseWfFormRecordPerson<WfFormRecordPerson> {
	
}
