package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormCusSecondaryContactInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormCusSecondaryContactInfo extends BaseWfFormCusSecondaryContactInfo<WfFormCusSecondaryContactInfo> {
	
}
