package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormEmployeeV1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormEmployeeV1 extends BaseWfFormEmployeeV1<WfFormEmployeeV1> {
	
}
