package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormContractPrintV1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormContractPrintV1 extends BaseWfFormContractPrintV1<WfFormContractPrintV1> {
	
}
