package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormGooutHomevisitV1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormGooutHomevisitV1 extends BaseWfFormGooutHomevisitV1<WfFormGooutHomevisitV1> {
	
}
