package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormContractPrintV2;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormContractPrintV2 extends BaseWfFormContractPrintV2<WfFormContractPrintV2> {
	
}
