package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormSalaryDetailV1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormSalaryDetailV1 extends BaseWfFormSalaryDetailV1<WfFormSalaryDetailV1> {
	
}
