package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormCusServiceContract;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormCusServiceContract extends BaseWfFormCusServiceContract<WfFormCusServiceContract> {
	
}
