package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormCarCustomerV1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormCarCustomerV1 extends BaseWfFormCarCustomerV1<WfFormCarCustomerV1> {
	
}
