package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormEmployeeBaseSalaryV1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormEmployeeBaseSalaryV1 extends BaseWfFormEmployeeBaseSalaryV1<WfFormEmployeeBaseSalaryV1> {
	
}
