package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormToLoanV1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormToLoanV1 extends BaseWfFormToLoanV1<WfFormToLoanV1> {
	
}
