package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormContractFaceTrialV2;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormContractFaceTrialV2 extends BaseWfFormContractFaceTrialV2<WfFormContractFaceTrialV2> {
	
}
