package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfFormWorkExperienceV1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfFormWorkExperienceV1 extends BaseWfFormWorkExperienceV1<WfFormWorkExperienceV1> {
	
}
