package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfWorkFlowData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfWorkFlowData extends BaseWfWorkFlowData<WfWorkFlowData> {
	
}
