package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfWorkFlowStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfWorkFlowStatus extends BaseWfWorkFlowStatus<WfWorkFlowStatus> {
	
}
