package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfWorkFlowType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfWorkFlowType extends BaseWfWorkFlowType<WfWorkFlowType> {
	
}
