package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfWorkFlowTypeFlow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfWorkFlowTypeFlow extends BaseWfWorkFlowTypeFlow<WfWorkFlowTypeFlow> {
	
}
