package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfWorkFlow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfWorkFlow extends BaseWfWorkFlow<WfWorkFlow> {
	
}
