package com.jyd.common.model;

import com.jyd.common.model.base.BaseWfWorkFlowOptionalProcessor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WfWorkFlowOptionalProcessor extends BaseWfWorkFlowOptionalProcessor<WfWorkFlowOptionalProcessor> {
	
}
