package com.jyd.common.model;

import com.jyd.common.model.base.BaseXiaomiTest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XiaomiTest extends BaseXiaomiTest<XiaomiTest> {
	
}
