package com.jyd.common.model;

import com.jyd.common.model.base.BaseYxdContract;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YxdContract extends BaseYxdContract<YxdContract> {
	
}
