package com.jyd.common.model;

import com.jyd.common.model.base.BaseYxdCustomerContact;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YxdCustomerContact extends BaseYxdCustomerContact<YxdCustomerContact> {
	
}
