package com.jyd.common.model;

import com.jyd.common.model.base.BaseYxdCustomerInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YxdCustomerInfo extends BaseYxdCustomerInfo<YxdCustomerInfo> {
	
}
