package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSchTaskLog<M extends BaseSchTaskLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setScheduleTypeId(java.lang.Integer scheduleTypeId) {
		set("schedule_type_id", scheduleTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getScheduleTypeId() {
		return getInt("schedule_type_id");
	}

	public M setRunDate(java.util.Date runDate) {
		set("run_date", runDate);
		return (M)this;
	}
	
	public java.util.Date getRunDate() {
		return get("run_date");
	}

	public M setBeginTime(java.util.Date beginTime) {
		set("begin_time", beginTime);
		return (M)this;
	}
	
	public java.util.Date getBeginTime() {
		return get("begin_time");
	}

	public M setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
		return (M)this;
	}
	
	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public M setElapsedTime(java.lang.String elapsedTime) {
		set("elapsed_time", elapsedTime);
		return (M)this;
	}
	
	public java.lang.String getElapsedTime() {
		return getStr("elapsed_time");
	}

}
