package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBaStore<M extends BaseBaStore<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setShortName(java.lang.String shortName) {
		set("short_name", shortName);
		return (M)this;
	}
	
	public java.lang.String getShortName() {
		return getStr("short_name");
	}

	public M setNum(java.lang.String num) {
		set("num", num);
		return (M)this;
	}
	
	public java.lang.String getNum() {
		return getStr("num");
	}

	public M setRegisteredName(java.lang.String registeredName) {
		set("registered_name", registeredName);
		return (M)this;
	}
	
	public java.lang.String getRegisteredName() {
		return getStr("registered_name");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setPrincipal(java.lang.String principal) {
		set("principal", principal);
		return (M)this;
	}
	
	public java.lang.String getPrincipal() {
		return getStr("principal");
	}

	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}
	
	public java.lang.String getProvince() {
		return getStr("province");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}
	
	public java.lang.String getCity() {
		return getStr("city");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setEmailAddress(java.lang.String emailAddress) {
		set("email_address", emailAddress);
		return (M)this;
	}
	
	public java.lang.String getEmailAddress() {
		return getStr("email_address");
	}

	public M setPrincipalBankNo(java.lang.String principalBankNo) {
		set("principal_bank_no", principalBankNo);
		return (M)this;
	}
	
	public java.lang.String getPrincipalBankNo() {
		return getStr("principal_bank_no");
	}

	public M setPrincipalBankName(java.lang.String principalBankName) {
		set("principal_bank_name", principalBankName);
		return (M)this;
	}
	
	public java.lang.String getPrincipalBankName() {
		return getStr("principal_bank_name");
	}

}
