package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWfFormCusServiceContract<M extends BaseWfFormCusServiceContract<M>> extends Model<M> implements IBean {

	public M setDataKey(java.lang.String dataKey) {
		set("data_key", dataKey);
		return (M)this;
	}
	
	public java.lang.String getDataKey() {
		return getStr("data_key");
	}

	public M setCusName(java.lang.String cusName) {
		set("cus_name", cusName);
		return (M)this;
	}
	
	public java.lang.String getCusName() {
		return getStr("cus_name");
	}

	public M setCusIdNo(java.lang.String cusIdNo) {
		set("cus_id_no", cusIdNo);
		return (M)this;
	}
	
	public java.lang.String getCusIdNo() {
		return getStr("cus_id_no");
	}

	public M setCusAddress(java.lang.String cusAddress) {
		set("cus_address", cusAddress);
		return (M)this;
	}
	
	public java.lang.String getCusAddress() {
		return getStr("cus_address");
	}

	public M setCusPhone(java.lang.String cusPhone) {
		set("cus_phone", cusPhone);
		return (M)this;
	}
	
	public java.lang.String getCusPhone() {
		return getStr("cus_phone");
	}

	public M setCusBankNo(java.lang.String cusBankNo) {
		set("cus_bank_no", cusBankNo);
		return (M)this;
	}
	
	public java.lang.String getCusBankNo() {
		return getStr("cus_bank_no");
	}

	public M setCusContractNo(java.lang.String cusContractNo) {
		set("cus_contract_no", cusContractNo);
		return (M)this;
	}
	
	public java.lang.String getCusContractNo() {
		return getStr("cus_contract_no");
	}

	public M setProductId(java.lang.Integer productId) {
		set("product_id", productId);
		return (M)this;
	}
	
	public java.lang.Integer getProductId() {
		return getInt("product_id");
	}

	public M setBorrowingPurpose(java.lang.String borrowingPurpose) {
		set("borrowing_purpose", borrowingPurpose);
		return (M)this;
	}
	
	public java.lang.String getBorrowingPurpose() {
		return getStr("borrowing_purpose");
	}

	public M setBorrowingAmount(java.math.BigDecimal borrowingAmount) {
		set("borrowing_amount", borrowingAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getBorrowingAmount() {
		return get("borrowing_amount");
	}

	public M setRepaymentStageId(java.lang.Integer repaymentStageId) {
		set("repayment_stage_id", repaymentStageId);
		return (M)this;
	}
	
	public java.lang.Integer getRepaymentStageId() {
		return getInt("repayment_stage_id");
	}

	public M setContractVersionId(java.lang.Integer contractVersionId) {
		set("contract_version_id", contractVersionId);
		return (M)this;
	}
	
	public java.lang.Integer getContractVersionId() {
		return getInt("contract_version_id");
	}

	public M setPlate(java.lang.String plate) {
		set("plate", plate);
		return (M)this;
	}
	
	public java.lang.String getPlate() {
		return getStr("plate");
	}

	public M setEngineNo(java.lang.String engineNo) {
		set("engine_no", engineNo);
		return (M)this;
	}
	
	public java.lang.String getEngineNo() {
		return getStr("engine_no");
	}

	public M setVin(java.lang.String vin) {
		set("vin", vin);
		return (M)this;
	}
	
	public java.lang.String getVin() {
		return getStr("vin");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setStartDate(java.util.Date startDate) {
		set("start_date", startDate);
		return (M)this;
	}
	
	public java.util.Date getStartDate() {
		return get("start_date");
	}

	public M setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
		return (M)this;
	}
	
	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public M setVehicleModel(java.lang.String vehicleModel) {
		set("vehicle_model", vehicleModel);
		return (M)this;
	}
	
	public java.lang.String getVehicleModel() {
		return getStr("vehicle_model");
	}

	public M setCusPersonalInfoId(java.lang.Integer cusPersonalInfoId) {
		set("cus_personal_info_id", cusPersonalInfoId);
		return (M)this;
	}
	
	public java.lang.Integer getCusPersonalInfoId() {
		return getInt("cus_personal_info_id");
	}

	public M setRepaymentAccountId(java.lang.Integer repaymentAccountId) {
		set("repayment_account_id", repaymentAccountId);
		return (M)this;
	}
	
	public java.lang.Integer getRepaymentAccountId() {
		return getInt("repayment_account_id");
	}

	public M setMortgagor(java.lang.String mortgagor) {
		set("mortgagor", mortgagor);
		return (M)this;
	}
	
	public java.lang.String getMortgagor() {
		return getStr("mortgagor");
	}

	public M setRepaymentAccount(java.lang.String repaymentAccount) {
		set("repayment_account", repaymentAccount);
		return (M)this;
	}
	
	public java.lang.String getRepaymentAccount() {
		return getStr("repayment_account");
	}

	public M setBankName(java.lang.String bankName) {
		set("bank_name", bankName);
		return (M)this;
	}
	
	public java.lang.String getBankName() {
		return getStr("bank_name");
	}

	public M setBrand(java.lang.String brand) {
		set("brand", brand);
		return (M)this;
	}
	
	public java.lang.String getBrand() {
		return getStr("brand");
	}

	public M setMortgagorIdcard(java.lang.String mortgagorIdcard) {
		set("mortgagor_idcard", mortgagorIdcard);
		return (M)this;
	}
	
	public java.lang.String getMortgagorIdcard() {
		return getStr("mortgagor_idcard");
	}

	public M setMortgagorAdress(java.lang.String mortgagorAdress) {
		set("mortgagor_adress", mortgagorAdress);
		return (M)this;
	}
	
	public java.lang.String getMortgagorAdress() {
		return getStr("mortgagor_adress");
	}

	public M setRepaymentBankName(java.lang.String repaymentBankName) {
		set("repayment_bank_name", repaymentBankName);
		return (M)this;
	}
	
	public java.lang.String getRepaymentBankName() {
		return getStr("repayment_bank_name");
	}

	public M setMortgagerId(java.lang.Integer mortgagerId) {
		set("mortgager_id", mortgagerId);
		return (M)this;
	}
	
	public java.lang.Integer getMortgagerId() {
		return getInt("mortgager_id");
	}

	public M setRepaymentName(java.lang.String repaymentName) {
		set("repayment_name", repaymentName);
		return (M)this;
	}
	
	public java.lang.String getRepaymentName() {
		return getStr("repayment_name");
	}

	public M setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
		return (M)this;
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public M setVehiclerinfoId(java.lang.Integer vehiclerinfoId) {
		set("vehiclerinfo_id", vehiclerinfoId);
		return (M)this;
	}
	
	public java.lang.Integer getVehiclerinfoId() {
		return getInt("vehiclerinfo_id");
	}

	public M setCarValuation(java.math.BigDecimal carValuation) {
		set("car_valuation", carValuation);
		return (M)this;
	}
	
	public java.math.BigDecimal getCarValuation() {
		return get("car_valuation");
	}

	public M setPurchasePrice(java.math.BigDecimal purchasePrice) {
		set("purchase_price", purchasePrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getPurchasePrice() {
		return get("purchase_price");
	}

	public M setPrincipal(java.math.BigDecimal principal) {
		set("principal", principal);
		return (M)this;
	}
	
	public java.math.BigDecimal getPrincipal() {
		return get("principal");
	}

	public M setLateFee(java.math.BigDecimal lateFee) {
		set("late_fee", lateFee);
		return (M)this;
	}
	
	public java.math.BigDecimal getLateFee() {
		return get("late_fee");
	}

	public M setExpLoanAmonut(java.math.BigDecimal expLoanAmonut) {
		set("exp_loan_amonut", expLoanAmonut);
		return (M)this;
	}
	
	public java.math.BigDecimal getExpLoanAmonut() {
		return get("exp_loan_amonut");
	}

	public M setEmployeeId(java.lang.Integer employeeId) {
		set("employee_id", employeeId);
		return (M)this;
	}
	
	public java.lang.Integer getEmployeeId() {
		return getInt("employee_id");
	}

	public M setPersonResponsibleId(java.lang.Integer personResponsibleId) {
		set("person_responsible_id", personResponsibleId);
		return (M)this;
	}
	
	public java.lang.Integer getPersonResponsibleId() {
		return getInt("person_responsible_id");
	}

	public M setSettlementDate(java.util.Date settlementDate) {
		set("settlement_date", settlementDate);
		return (M)this;
	}
	
	public java.util.Date getSettlementDate() {
		return get("settlement_date");
	}

	public M setAssetsTypeId(java.lang.Integer assetsTypeId) {
		set("assets_type_id", assetsTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getAssetsTypeId() {
		return getInt("assets_type_id");
	}

	public M setBusinessSourceId(java.lang.Integer businessSourceId) {
		set("business_source_id", businessSourceId);
		return (M)this;
	}
	
	public java.lang.Integer getBusinessSourceId() {
		return getInt("business_source_id");
	}

	public M setOverdueDays(java.lang.Integer overdueDays) {
		set("overdue_days", overdueDays);
		return (M)this;
	}
	
	public java.lang.Integer getOverdueDays() {
		return getInt("overdue_days");
	}

	public M setMentionPay(java.math.BigDecimal mentionPay) {
		set("mentionPay", mentionPay);
		return (M)this;
	}
	
	public java.math.BigDecimal getMentionPay() {
		return get("mentionPay");
	}

	public M setSellerDefaultDate(java.util.Date sellerDefaultDate) {
		set("seller_default_date", sellerDefaultDate);
		return (M)this;
	}
	
	public java.util.Date getSellerDefaultDate() {
		return get("seller_default_date");
	}

	public M setTrailCarDate(java.util.Date trailCarDate) {
		set("trail_car_date", trailCarDate);
		return (M)this;
	}
	
	public java.util.Date getTrailCarDate() {
		return get("trail_car_date");
	}

	public M setSellCarDate(java.util.Date sellCarDate) {
		set("sell_car_date", sellCarDate);
		return (M)this;
	}
	
	public java.util.Date getSellCarDate() {
		return get("sell_car_date");
	}

	public M setSellCarAmount(java.math.BigDecimal sellCarAmount) {
		set("sell_car_amount", sellCarAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getSellCarAmount() {
		return get("sell_car_amount");
	}

	public M setCollectPrincipal(java.math.BigDecimal collectPrincipal) {
		set("collect_principal", collectPrincipal);
		return (M)this;
	}
	
	public java.math.BigDecimal getCollectPrincipal() {
		return get("collect_principal");
	}

	public M setCollectInterest(java.math.BigDecimal collectInterest) {
		set("collect_interest", collectInterest);
		return (M)this;
	}
	
	public java.math.BigDecimal getCollectInterest() {
		return get("collect_interest");
	}

	public M setCollectLatefee(java.math.BigDecimal collectLatefee) {
		set("collect_latefee", collectLatefee);
		return (M)this;
	}
	
	public java.math.BigDecimal getCollectLatefee() {
		return get("collect_latefee");
	}

	public M setHasflagPrincipal(java.math.BigDecimal hasflagPrincipal) {
		set("hasFlag_principal", hasflagPrincipal);
		return (M)this;
	}
	
	public java.math.BigDecimal getHasflagPrincipal() {
		return get("hasFlag_principal");
	}

	public M setHasflagInterest(java.math.BigDecimal hasflagInterest) {
		set("hasFlag_interest", hasflagInterest);
		return (M)this;
	}
	
	public java.math.BigDecimal getHasflagInterest() {
		return get("hasFlag_interest");
	}

	public M setHasflagLatafee(java.math.BigDecimal hasflagLatafee) {
		set("hasFlag_latafee", hasflagLatafee);
		return (M)this;
	}
	
	public java.math.BigDecimal getHasflagLatafee() {
		return get("hasFlag_latafee");
	}

}
