package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseHrDepartment<M extends BaseHrDepartment<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setDepartmentName(java.lang.String departmentName) {
		set("department_name", departmentName);
		return (M)this;
	}
	
	public java.lang.String getDepartmentName() {
		return getStr("department_name");
	}

	public M setDepartmentSupervisor(java.lang.Integer departmentSupervisor) {
		set("department_supervisor", departmentSupervisor);
		return (M)this;
	}
	
	public java.lang.Integer getDepartmentSupervisor() {
		return getInt("department_supervisor");
	}

	public M setActualNums(java.lang.Integer actualNums) {
		set("actual_nums", actualNums);
		return (M)this;
	}
	
	public java.lang.Integer getActualNums() {
		return getInt("actual_nums");
	}

	public M setTotalActualNums(java.lang.Integer totalActualNums) {
		set("total_actual_nums", totalActualNums);
		return (M)this;
	}
	
	public java.lang.Integer getTotalActualNums() {
		return getInt("total_actual_nums");
	}

	public M setStaffNums(java.lang.Integer staffNums) {
		set("staff_nums", staffNums);
		return (M)this;
	}
	
	public java.lang.Integer getStaffNums() {
		return getInt("staff_nums");
	}

	public M setTotalStaffNums(java.lang.Integer totalStaffNums) {
		set("total_staff_nums", totalStaffNums);
		return (M)this;
	}
	
	public java.lang.Integer getTotalStaffNums() {
		return getInt("total_staff_nums");
	}

	public M setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
		return (M)this;
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	public M setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
		return (M)this;
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setDepartmentTypeId(java.lang.Integer departmentTypeId) {
		set("department_type_id", departmentTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getDepartmentTypeId() {
		return getInt("department_type_id");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

}
