package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAttShiftWorktime<M extends BaseAttShiftWorktime<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setShiftId(java.lang.Integer shiftId) {
		set("shift_id", shiftId);
		return (M)this;
	}
	
	public java.lang.Integer getShiftId() {
		return getInt("shift_id");
	}

	public M setWorkTimeId(java.lang.Integer workTimeId) {
		set("work_time_id", workTimeId);
		return (M)this;
	}
	
	public java.lang.Integer getWorkTimeId() {
		return getInt("work_time_id");
	}

}
