package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCusGpsinstall<M extends BaseCusGpsinstall<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
		return (M)this;
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public M setInstallDate(java.util.Date installDate) {
		set("install_date", installDate);
		return (M)this;
	}
	
	public java.util.Date getInstallDate() {
		return get("install_date");
	}

	public M setInstallMaster(java.lang.String installMaster) {
		set("install_master", installMaster);
		return (M)this;
	}
	
	public java.lang.String getInstallMaster() {
		return getStr("install_master");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setEquipmentId(java.lang.Integer equipmentId) {
		set("equipment_id", equipmentId);
		return (M)this;
	}
	
	public java.lang.Integer getEquipmentId() {
		return getInt("equipment_id");
	}

	public M setCarplate(java.lang.String carplate) {
		set("carplate", carplate);
		return (M)this;
	}
	
	public java.lang.String getCarplate() {
		return getStr("carplate");
	}

	public M setCusContractId(java.lang.Integer cusContractId) {
		set("cus_contract_id", cusContractId);
		return (M)this;
	}
	
	public java.lang.Integer getCusContractId() {
		return getInt("cus_contract_id");
	}

	public M setCarModel(java.lang.String carModel) {
		set("car_model", carModel);
		return (M)this;
	}
	
	public java.lang.String getCarModel() {
		return getStr("car_model");
	}

}
