package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCusThirdpartGpsVehicleBaseData<M extends BaseCusThirdpartGpsVehicleBaseData<M>> extends Model<M> implements IBean {

	public M setCusThirdpartGpsVehicleBaseDataId(java.lang.Long cusThirdpartGpsVehicleBaseDataId) {
		set("cus_thirdpart_gps_vehicle_base_data_id", cusThirdpartGpsVehicleBaseDataId);
		return (M)this;
	}
	
	public java.lang.Long getCusThirdpartGpsVehicleBaseDataId() {
		return getLong("cus_thirdpart_gps_vehicle_base_data_id");
	}

	public M setVehicleId(java.lang.String vehicleId) {
		set("vehicle_id", vehicleId);
		return (M)this;
	}
	
	public java.lang.String getVehicleId() {
		return getStr("vehicle_id");
	}

	public M setPlate(java.lang.String plate) {
		set("plate", plate);
		return (M)this;
	}
	
	public java.lang.String getPlate() {
		return getStr("plate");
	}

	public M setTerminalNo(java.lang.String terminalNo) {
		set("terminalNo", terminalNo);
		return (M)this;
	}
	
	public java.lang.String getTerminalNo() {
		return getStr("terminalNo");
	}

	public M setSim(java.lang.String sim) {
		set("sim", sim);
		return (M)this;
	}
	
	public java.lang.String getSim() {
		return getStr("sim");
	}

	public M setTerminalType(java.lang.String terminalType) {
		set("terminalType", terminalType);
		return (M)this;
	}
	
	public java.lang.String getTerminalType() {
		return getStr("terminalType");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

}
