package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCusContractRepayment<M extends BaseCusContractRepayment<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCusContractStageId(java.lang.Integer cusContractStageId) {
		set("cus_contract_stage_id", cusContractStageId);
		return (M)this;
	}
	
	public java.lang.Integer getCusContractStageId() {
		return getInt("cus_contract_stage_id");
	}

	public M setRepaymentFee(java.math.BigDecimal repaymentFee) {
		set("repayment_fee", repaymentFee);
		return (M)this;
	}
	
	public java.math.BigDecimal getRepaymentFee() {
		return get("repayment_fee");
	}

	public M setRepaymentDate(java.util.Date repaymentDate) {
		set("repayment_date", repaymentDate);
		return (M)this;
	}
	
	public java.util.Date getRepaymentDate() {
		return get("repayment_date");
	}

	public M setPayment(java.lang.String payment) {
		set("payment", payment);
		return (M)this;
	}
	
	public java.lang.String getPayment() {
		return getStr("payment");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCapital(java.math.BigDecimal capital) {
		set("capital", capital);
		return (M)this;
	}
	
	public java.math.BigDecimal getCapital() {
		return get("capital");
	}

	public M setLessStill(java.math.BigDecimal lessStill) {
		set("less_still", lessStill);
		return (M)this;
	}
	
	public java.math.BigDecimal getLessStill() {
		return get("less_still");
	}

	public M setMuchMore(java.math.BigDecimal muchMore) {
		set("much_more", muchMore);
		return (M)this;
	}
	
	public java.math.BigDecimal getMuchMore() {
		return get("much_more");
	}

	public M setInterest(java.math.BigDecimal interest) {
		set("interest", interest);
		return (M)this;
	}
	
	public java.math.BigDecimal getInterest() {
		return get("interest");
	}

	public M setDamagesAmount(java.math.BigDecimal damagesAmount) {
		set("damages_amount", damagesAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getDamagesAmount() {
		return get("damages_amount");
	}

	public M setLateFee(java.math.BigDecimal lateFee) {
		set("lateFee", lateFee);
		return (M)this;
	}
	
	public java.math.BigDecimal getLateFee() {
		return get("lateFee");
	}

	public M setExtraCharges(java.math.BigDecimal extraCharges) {
		set("extra_charges", extraCharges);
		return (M)this;
	}
	
	public java.math.BigDecimal getExtraCharges() {
		return get("extra_charges");
	}

	public M setIsLock(java.lang.Integer isLock) {
		set("is_lock", isLock);
		return (M)this;
	}
	
	public java.lang.Integer getIsLock() {
		return getInt("is_lock");
	}

	public M setLockUser(java.lang.String lockUser) {
		set("lock_user", lockUser);
		return (M)this;
	}
	
	public java.lang.String getLockUser() {
		return getStr("lock_user");
	}

	public M setFeeSource(java.lang.Integer feeSource) {
		set("fee_source", feeSource);
		return (M)this;
	}
	
	public java.lang.Integer getFeeSource() {
		return getInt("fee_source");
	}

}
