package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWfWorkFlowStatus<M extends BaseWfWorkFlowStatus<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setWorkFlowId(java.lang.Integer workFlowId) {
		set("work_flow_id", workFlowId);
		return (M)this;
	}
	
	public java.lang.Integer getWorkFlowId() {
		return getInt("work_flow_id");
	}

	public M setNodeName(java.lang.String nodeName) {
		set("node_name", nodeName);
		return (M)this;
	}
	
	public java.lang.String getNodeName() {
		return getStr("node_name");
	}

	public M setFormId(java.lang.Integer formId) {
		set("form_id", formId);
		return (M)this;
	}
	
	public java.lang.Integer getFormId() {
		return getInt("form_id");
	}

	public M setFormData(java.lang.String formData) {
		set("form_data", formData);
		return (M)this;
	}
	
	public java.lang.String getFormData() {
		return getStr("form_data");
	}

	public M setFlowId(java.lang.Integer flowId) {
		set("flow_id", flowId);
		return (M)this;
	}
	
	public java.lang.Integer getFlowId() {
		return getInt("flow_id");
	}

	public M setProcessEmployeeId(java.lang.Integer processEmployeeId) {
		set("process_employee_id", processEmployeeId);
		return (M)this;
	}
	
	public java.lang.Integer getProcessEmployeeId() {
		return getInt("process_employee_id");
	}

	public M setMultiUserFlag(java.lang.Integer multiUserFlag) {
		set("multi_user_flag", multiUserFlag);
		return (M)this;
	}
	
	public java.lang.Integer getMultiUserFlag() {
		return getInt("multi_user_flag");
	}

	public M setDecision(java.lang.Integer decision) {
		set("decision", decision);
		return (M)this;
	}
	
	public java.lang.Integer getDecision() {
		return getInt("decision");
	}

	public M setDecisionContent(java.lang.Integer decisionContent) {
		set("decision_content", decisionContent);
		return (M)this;
	}
	
	public java.lang.Integer getDecisionContent() {
		return getInt("decision_content");
	}

	public M setArriveTime(java.util.Date arriveTime) {
		set("arrive_time", arriveTime);
		return (M)this;
	}
	
	public java.util.Date getArriveTime() {
		return get("arrive_time");
	}

	public M setBeginTime(java.util.Date beginTime) {
		set("begin_time", beginTime);
		return (M)this;
	}
	
	public java.util.Date getBeginTime() {
		return get("begin_time");
	}

	public M setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
		return (M)this;
	}
	
	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public M setFeedback(java.lang.String feedback) {
		set("feedback", feedback);
		return (M)this;
	}
	
	public java.lang.String getFeedback() {
		return getStr("feedback");
	}

	public M setSortIndex(java.lang.Integer sortIndex) {
		set("sort_index", sortIndex);
		return (M)this;
	}
	
	public java.lang.Integer getSortIndex() {
		return getInt("sort_index");
	}

	public M setFlowData(java.lang.Integer flowData) {
		set("flow_data", flowData);
		return (M)this;
	}
	
	public java.lang.Integer getFlowData() {
		return getInt("flow_data");
	}

	public M setDistinctStore(java.lang.Integer distinctStore) {
		set("distinct_store", distinctStore);
		return (M)this;
	}
	
	public java.lang.Integer getDistinctStore() {
		return getInt("distinct_store");
	}

	public M setEntryDepartment(java.lang.Integer entryDepartment) {
		set("entry_department", entryDepartment);
		return (M)this;
	}
	
	public java.lang.Integer getEntryDepartment() {
		return getInt("entry_department");
	}

	public M setMajorDepartment(java.lang.Integer majorDepartment) {
		set("major_department", majorDepartment);
		return (M)this;
	}
	
	public java.lang.Integer getMajorDepartment() {
		return getInt("major_department");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setProcessorStatus(java.lang.Integer processorStatus) {
		set("processor_status", processorStatus);
		return (M)this;
	}
	
	public java.lang.Integer getProcessorStatus() {
		return getInt("processor_status");
	}

	public M setWfWorkFlowTypeFlowId(java.lang.Integer wfWorkFlowTypeFlowId) {
		set("wf_work_flow_type_flow_id", wfWorkFlowTypeFlowId);
		return (M)this;
	}
	
	public java.lang.Integer getWfWorkFlowTypeFlowId() {
		return getInt("wf_work_flow_type_flow_id");
	}

	public M setTempStatus(java.lang.Integer tempStatus) {
		set("temp_status", tempStatus);
		return (M)this;
	}
	
	public java.lang.Integer getTempStatus() {
		return getInt("temp_status");
	}

}
