package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseHbaseMapType<M extends BaseHbaseMapType<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setKeyName(java.lang.String keyName) {
		set("key_name", keyName);
		return (M)this;
	}
	
	public java.lang.String getKeyName() {
		return getStr("key_name");
	}

	public M setKeyValue(java.lang.String keyValue) {
		set("key_value", keyValue);
		return (M)this;
	}
	
	public java.lang.String getKeyValue() {
		return getStr("key_value");
	}

	public M setValue(java.lang.String value) {
		set("value", value);
		return (M)this;
	}
	
	public java.lang.String getValue() {
		return getStr("value");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

}
