package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCusContractGpsLateFee<M extends BaseCusContractGpsLateFee<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCusContractId(java.lang.Integer cusContractId) {
		set("cus_contract_id", cusContractId);
		return (M)this;
	}
	
	public java.lang.Integer getCusContractId() {
		return getInt("cus_contract_id");
	}

	public M setValue(java.math.BigDecimal value) {
		set("value", value);
		return (M)this;
	}
	
	public java.math.BigDecimal getValue() {
		return get("value");
	}

	public M setGpsCostTypeId(java.lang.Integer gpsCostTypeId) {
		set("gps_cost_type_id", gpsCostTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getGpsCostTypeId() {
		return getInt("gps_cost_type_id");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setParkingFeeId(java.lang.Integer parkingFeeId) {
		set("parking_fee_id", parkingFeeId);
		return (M)this;
	}
	
	public java.lang.Integer getParkingFeeId() {
		return getInt("parking_fee_id");
	}

}
