package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAttScheduling<M extends BaseAttScheduling<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setEmployeeId(java.lang.Integer employeeId) {
		set("employee_id", employeeId);
		return (M)this;
	}
	
	public java.lang.Integer getEmployeeId() {
		return getInt("employee_id");
	}

	public M setShiftId(java.lang.Integer shiftId) {
		set("shift_id", shiftId);
		return (M)this;
	}
	
	public java.lang.Integer getShiftId() {
		return getInt("shift_id");
	}

	public M setShiftDate(java.util.Date shiftDate) {
		set("shift_date", shiftDate);
		return (M)this;
	}
	
	public java.util.Date getShiftDate() {
		return get("shift_date");
	}

}
