package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCusContractStage<M extends BaseCusContractStage<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setStage(java.lang.Integer stage) {
		set("stage", stage);
		return (M)this;
	}
	
	public java.lang.Integer getStage() {
		return getInt("stage");
	}

	public M setCusContractId(java.lang.Integer cusContractId) {
		set("cus_contract_id", cusContractId);
		return (M)this;
	}
	
	public java.lang.Integer getCusContractId() {
		return getInt("cus_contract_id");
	}

	public M setCapital(java.math.BigDecimal capital) {
		set("capital", capital);
		return (M)this;
	}
	
	public java.math.BigDecimal getCapital() {
		return get("capital");
	}

	public M setInterest(java.math.BigDecimal interest) {
		set("interest", interest);
		return (M)this;
	}
	
	public java.math.BigDecimal getInterest() {
		return get("interest");
	}

	public M setExtraCharges(java.math.BigDecimal extraCharges) {
		set("extra_charges", extraCharges);
		return (M)this;
	}
	
	public java.math.BigDecimal getExtraCharges() {
		return get("extra_charges");
	}

	public M setRepaymentDate(java.util.Date repaymentDate) {
		set("repayment_date", repaymentDate);
		return (M)this;
	}
	
	public java.util.Date getRepaymentDate() {
		return get("repayment_date");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setRealRepaymentDate(java.util.Date realRepaymentDate) {
		set("real_repayment_date", realRepaymentDate);
		return (M)this;
	}
	
	public java.util.Date getRealRepaymentDate() {
		return get("real_repayment_date");
	}

}
