package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSalEmployeeBaseSalaryHistory<M extends BaseSalEmployeeBaseSalaryHistory<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setEmployeeSalaryHistoryId(java.lang.Integer employeeSalaryHistoryId) {
		set("employee_salary_history_id", employeeSalaryHistoryId);
		return (M)this;
	}
	
	public java.lang.Integer getEmployeeSalaryHistoryId() {
		return getInt("employee_salary_history_id");
	}

	public M setEmployeeId(java.lang.Integer employeeId) {
		set("employee_id", employeeId);
		return (M)this;
	}
	
	public java.lang.Integer getEmployeeId() {
		return getInt("employee_id");
	}

	public M setBaseSalaryItemId(java.lang.Integer baseSalaryItemId) {
		set("base_salary_item_id", baseSalaryItemId);
		return (M)this;
	}
	
	public java.lang.Integer getBaseSalaryItemId() {
		return getInt("base_salary_item_id");
	}

	public M setValue(java.lang.String value) {
		set("value", value);
		return (M)this;
	}
	
	public java.lang.String getValue() {
		return getStr("value");
	}

}
