package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCusVehicleInfo<M extends BaseCusVehicleInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setBrand(java.lang.String brand) {
		set("brand", brand);
		return (M)this;
	}
	
	public java.lang.String getBrand() {
		return getStr("brand");
	}

	public M setColor(java.lang.String color) {
		set("color", color);
		return (M)this;
	}
	
	public java.lang.String getColor() {
		return getStr("color");
	}

	public M setInitialDateOfRegistration(java.util.Date initialDateOfRegistration) {
		set("initial_date_of_registration", initialDateOfRegistration);
		return (M)this;
	}
	
	public java.util.Date getInitialDateOfRegistration() {
		return get("initial_date_of_registration");
	}

	public M setPlate(java.lang.String plate) {
		set("plate", plate);
		return (M)this;
	}
	
	public java.lang.String getPlate() {
		return getStr("plate");
	}

	public M setEngineNo(java.lang.String engineNo) {
		set("engine_no", engineNo);
		return (M)this;
	}
	
	public java.lang.String getEngineNo() {
		return getStr("engine_no");
	}

	public M setVin(java.lang.String vin) {
		set("vin", vin);
		return (M)this;
	}
	
	public java.lang.String getVin() {
		return getStr("vin");
	}

	public M setPurchasePrice(java.math.BigDecimal purchasePrice) {
		set("purchase_price", purchasePrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getPurchasePrice() {
		return get("purchase_price");
	}

	public M setMilesOfTraveled(java.lang.Integer milesOfTraveled) {
		set("miles_of_traveled", milesOfTraveled);
		return (M)this;
	}
	
	public java.lang.Integer getMilesOfTraveled() {
		return getInt("miles_of_traveled");
	}

	public M setInsuranceExpirationDate(java.util.Date insuranceExpirationDate) {
		set("insurance_expiration_date", insuranceExpirationDate);
		return (M)this;
	}
	
	public java.util.Date getInsuranceExpirationDate() {
		return get("insurance_expiration_date");
	}

	public M setAnnualRiskDueDate(java.util.Date annualRiskDueDate) {
		set("annual_risk_due_date", annualRiskDueDate);
		return (M)this;
	}
	
	public java.util.Date getAnnualRiskDueDate() {
		return get("annual_risk_due_date");
	}

	public M setCusId(java.lang.Integer cusId) {
		set("cus_id", cusId);
		return (M)this;
	}
	
	public java.lang.Integer getCusId() {
		return getInt("cus_id");
	}

	public M setVehicleTypeId(java.lang.Integer vehicleTypeId) {
		set("vehicle_type_id", vehicleTypeId);
		return (M)this;
	}
	
	public java.lang.Integer getVehicleTypeId() {
		return getInt("vehicle_type_id");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setCarValuation(java.math.BigDecimal carValuation) {
		set("car_valuation", carValuation);
		return (M)this;
	}
	
	public java.math.BigDecimal getCarValuation() {
		return get("car_valuation");
	}

	public M setReleaseDate(java.util.Date releaseDate) {
		set("release_date", releaseDate);
		return (M)this;
	}
	
	public java.util.Date getReleaseDate() {
		return get("release_date");
	}

	public M setGearbox(java.lang.String gearbox) {
		set("gearbox", gearbox);
		return (M)this;
	}
	
	public java.lang.String getGearbox() {
		return getStr("gearbox");
	}

	public M setDisplacement(java.lang.String displacement) {
		set("displacement", displacement);
		return (M)this;
	}
	
	public java.lang.String getDisplacement() {
		return getStr("displacement");
	}

	public M setEmissions(java.lang.String emissions) {
		set("emissions", emissions);
		return (M)this;
	}
	
	public java.lang.String getEmissions() {
		return getStr("emissions");
	}

	public M setVehicleLevel(java.lang.String vehicleLevel) {
		set("vehicle_level", vehicleLevel);
		return (M)this;
	}
	
	public java.lang.String getVehicleLevel() {
		return getStr("vehicle_level");
	}

	public M setDoor(java.lang.String door) {
		set("door", door);
		return (M)this;
	}
	
	public java.lang.String getDoor() {
		return getStr("door");
	}

	public M setOil(java.lang.String oil) {
		set("oil", oil);
		return (M)this;
	}
	
	public java.lang.String getOil() {
		return getStr("oil");
	}

	public M setDriveMode(java.lang.String driveMode) {
		set("drive_mode", driveMode);
		return (M)this;
	}
	
	public java.lang.String getDriveMode() {
		return getStr("drive_mode");
	}

	public M setTimeToMarket(java.util.Date timeToMarket) {
		set("time_to_market", timeToMarket);
		return (M)this;
	}
	
	public java.util.Date getTimeToMarket() {
		return get("time_to_market");
	}

	public M setAlloction(java.lang.String alloction) {
		set("alloction", alloction);
		return (M)this;
	}
	
	public java.lang.String getAlloction() {
		return getStr("alloction");
	}

	public M setModel(java.lang.String model) {
		set("model", model);
		return (M)this;
	}
	
	public java.lang.String getModel() {
		return getStr("model");
	}

	public M setTrimEvluate(java.lang.String trimEvluate) {
		set("trim_evluate", trimEvluate);
		return (M)this;
	}
	
	public java.lang.String getTrimEvluate() {
		return getStr("trim_evluate");
	}

	public M setSeat(java.lang.String seat) {
		set("seat", seat);
		return (M)this;
	}
	
	public java.lang.String getSeat() {
		return getStr("seat");
	}

	public M setTrim(java.lang.String trim) {
		set("trim", trim);
		return (M)this;
	}
	
	public java.lang.String getTrim() {
		return getStr("trim");
	}

	public M setCarBodyEvluate(java.lang.String carBodyEvluate) {
		set("car_body_evluate", carBodyEvluate);
		return (M)this;
	}
	
	public java.lang.String getCarBodyEvluate() {
		return getStr("car_body_evluate");
	}

	public M setMortgageRepaymentDate(java.util.Date mortgageRepaymentDate) {
		set("mortgage_repayment_date", mortgageRepaymentDate);
		return (M)this;
	}
	
	public java.util.Date getMortgageRepaymentDate() {
		return get("mortgage_repayment_date");
	}

	public M setMortgageDueDate(java.util.Date mortgageDueDate) {
		set("mortgage_due_date", mortgageDueDate);
		return (M)this;
	}
	
	public java.util.Date getMortgageDueDate() {
		return get("mortgage_due_date");
	}

}
