package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCusContractFaceTrial<M extends BaseCusContractFaceTrial<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setContractId(java.lang.Integer contractId) {
		set("contract_id", contractId);
		return (M)this;
	}
	
	public java.lang.Integer getContractId() {
		return getInt("contract_id");
	}

	public M setCompanyBussiness(java.lang.String companyBussiness) {
		set("company_bussiness", companyBussiness);
		return (M)this;
	}
	
	public java.lang.String getCompanyBussiness() {
		return getStr("company_bussiness");
	}

	public M setMonthSaleRoom(java.math.BigDecimal monthSaleRoom) {
		set("month_sale_room", monthSaleRoom);
		return (M)this;
	}
	
	public java.math.BigDecimal getMonthSaleRoom() {
		return get("month_sale_room");
	}

	public M setMachine(java.math.BigDecimal machine) {
		set("machine", machine);
		return (M)this;
	}
	
	public java.math.BigDecimal getMachine() {
		return get("machine");
	}

	public M setGrossProfitRate(java.math.BigDecimal grossProfitRate) {
		set("gross_profit_rate", grossProfitRate);
		return (M)this;
	}
	
	public java.math.BigDecimal getGrossProfitRate() {
		return get("gross_profit_rate");
	}

	public M setStoreMaterial(java.math.BigDecimal storeMaterial) {
		set("store_material", storeMaterial);
		return (M)this;
	}
	
	public java.math.BigDecimal getStoreMaterial() {
		return get("store_material");
	}

	public M setEmployeeWage(java.math.BigDecimal employeeWage) {
		set("employee_wage", employeeWage);
		return (M)this;
	}
	
	public java.math.BigDecimal getEmployeeWage() {
		return get("employee_wage");
	}

	public M setTotalEmployee(java.lang.Integer totalEmployee) {
		set("total_employee", totalEmployee);
		return (M)this;
	}
	
	public java.lang.Integer getTotalEmployee() {
		return getInt("total_employee");
	}

	public M setAccountReceivable(java.math.BigDecimal accountReceivable) {
		set("account_receivable", accountReceivable);
		return (M)this;
	}
	
	public java.math.BigDecimal getAccountReceivable() {
		return get("account_receivable");
	}

	public M setAccountPayable(java.math.BigDecimal accountPayable) {
		set("account_payable", accountPayable);
		return (M)this;
	}
	
	public java.math.BigDecimal getAccountPayable() {
		return get("account_payable");
	}

	public M setPlaceRental(java.math.BigDecimal placeRental) {
		set("place_rental", placeRental);
		return (M)this;
	}
	
	public java.math.BigDecimal getPlaceRental() {
		return get("place_rental");
	}

	public M setPlaceArea(java.math.BigDecimal placeArea) {
		set("place_area", placeArea);
		return (M)this;
	}
	
	public java.math.BigDecimal getPlaceArea() {
		return get("place_area");
	}

	public M setOtherCharge(java.math.BigDecimal otherCharge) {
		set("other_charge", otherCharge);
		return (M)this;
	}
	
	public java.math.BigDecimal getOtherCharge() {
		return get("other_charge");
	}

	public M setProfit(java.math.BigDecimal profit) {
		set("profit", profit);
		return (M)this;
	}
	
	public java.math.BigDecimal getProfit() {
		return get("profit");
	}

	public M setCompanyNature(java.lang.String companyNature) {
		set("company_nature", companyNature);
		return (M)this;
	}
	
	public java.lang.String getCompanyNature() {
		return getStr("company_nature");
	}

	public M setCompanyScale(java.lang.String companyScale) {
		set("company_scale", companyScale);
		return (M)this;
	}
	
	public java.lang.String getCompanyScale() {
		return getStr("company_scale");
	}

	public M setIndustry(java.lang.String industry) {
		set("industry", industry);
		return (M)this;
	}
	
	public java.lang.String getIndustry() {
		return getStr("industry");
	}

	public M setDepartment(java.lang.String department) {
		set("department", department);
		return (M)this;
	}
	
	public java.lang.String getDepartment() {
		return getStr("department");
	}

	public M setPosition(java.lang.String position) {
		set("position", position);
		return (M)this;
	}
	
	public java.lang.String getPosition() {
		return getStr("position");
	}

	public M setDuty(java.lang.String duty) {
		set("duty", duty);
		return (M)this;
	}
	
	public java.lang.String getDuty() {
		return getStr("duty");
	}

	public M setSalary(java.math.BigDecimal salary) {
		set("salary", salary);
		return (M)this;
	}
	
	public java.math.BigDecimal getSalary() {
		return get("salary");
	}

	public M setOtherEarning(java.math.BigDecimal otherEarning) {
		set("other_earning", otherEarning);
		return (M)this;
	}
	
	public java.math.BigDecimal getOtherEarning() {
		return get("other_earning");
	}

	public M setJoinDate(java.util.Date joinDate) {
		set("join_date", joinDate);
		return (M)this;
	}
	
	public java.util.Date getJoinDate() {
		return get("join_date");
	}

	public M setSalaryDate(java.lang.Integer salaryDate) {
		set("salary_date", salaryDate);
		return (M)this;
	}
	
	public java.lang.Integer getSalaryDate() {
		return getInt("salary_date");
	}

	public M setChildRemark(java.lang.String childRemark) {
		set("child_remark", childRemark);
		return (M)this;
	}
	
	public java.lang.String getChildRemark() {
		return getStr("child_remark");
	}

	public M setMateRemark(java.lang.String mateRemark) {
		set("mate_remark", mateRemark);
		return (M)this;
	}
	
	public java.lang.String getMateRemark() {
		return getStr("mate_remark");
	}

	public M setPersonalRemark(java.lang.String personalRemark) {
		set("personal_remark", personalRemark);
		return (M)this;
	}
	
	public java.lang.String getPersonalRemark() {
		return getStr("personal_remark");
	}

	public M setHousePropertyOne(java.math.BigDecimal housePropertyOne) {
		set("house_property_one", housePropertyOne);
		return (M)this;
	}
	
	public java.math.BigDecimal getHousePropertyOne() {
		return get("house_property_one");
	}

	public M setHouseAreaOne(java.math.BigDecimal houseAreaOne) {
		set("house_area_one", houseAreaOne);
		return (M)this;
	}
	
	public java.math.BigDecimal getHouseAreaOne() {
		return get("house_area_one");
	}

	public M setHouseOneAmountInArear(java.math.BigDecimal houseOneAmountInArear) {
		set("house_one_amount_in_arear", houseOneAmountInArear);
		return (M)this;
	}
	
	public java.math.BigDecimal getHouseOneAmountInArear() {
		return get("house_one_amount_in_arear");
	}

	public M setHousePropertyTwo(java.math.BigDecimal housePropertyTwo) {
		set("house_property_two", housePropertyTwo);
		return (M)this;
	}
	
	public java.math.BigDecimal getHousePropertyTwo() {
		return get("house_property_two");
	}

	public M setHouseAreaTwo(java.math.BigDecimal houseAreaTwo) {
		set("house_area_two", houseAreaTwo);
		return (M)this;
	}
	
	public java.math.BigDecimal getHouseAreaTwo() {
		return get("house_area_two");
	}

	public M setHouseTwoAmountInArear(java.math.BigDecimal houseTwoAmountInArear) {
		set("house_two_amount_in_arear", houseTwoAmountInArear);
		return (M)this;
	}
	
	public java.math.BigDecimal getHouseTwoAmountInArear() {
		return get("house_two_amount_in_arear");
	}

	public M setCarBrandOne(java.lang.String carBrandOne) {
		set("car_brand_one", carBrandOne);
		return (M)this;
	}
	
	public java.lang.String getCarBrandOne() {
		return getStr("car_brand_one");
	}

	public M setCarMarketPriceOne(java.math.BigDecimal carMarketPriceOne) {
		set("car_market_price_one", carMarketPriceOne);
		return (M)this;
	}
	
	public java.math.BigDecimal getCarMarketPriceOne() {
		return get("car_market_price_one");
	}

	public M setCarOneAmountInArear(java.math.BigDecimal carOneAmountInArear) {
		set("car_one_amount_in_arear", carOneAmountInArear);
		return (M)this;
	}
	
	public java.math.BigDecimal getCarOneAmountInArear() {
		return get("car_one_amount_in_arear");
	}

	public M setCarBrandTwo(java.lang.String carBrandTwo) {
		set("car_brand_two", carBrandTwo);
		return (M)this;
	}
	
	public java.lang.String getCarBrandTwo() {
		return getStr("car_brand_two");
	}

	public M setCarMarketPriceTwo(java.math.BigDecimal carMarketPriceTwo) {
		set("car_market_price_two", carMarketPriceTwo);
		return (M)this;
	}
	
	public java.math.BigDecimal getCarMarketPriceTwo() {
		return get("car_market_price_two");
	}

	public M setCarTwoAmountInArear(java.math.BigDecimal carTwoAmountInArear) {
		set("car_two_amount_in_arear", carTwoAmountInArear);
		return (M)this;
	}
	
	public java.math.BigDecimal getCarTwoAmountInArear() {
		return get("car_two_amount_in_arear");
	}

	public M setCreditCardBankNameOne(java.lang.String creditCardBankNameOne) {
		set("credit_card_bank_name_one", creditCardBankNameOne);
		return (M)this;
	}
	
	public java.lang.String getCreditCardBankNameOne() {
		return getStr("credit_card_bank_name_one");
	}

	public M setLimitOne(java.math.BigDecimal limitOne) {
		set("limit_one", limitOne);
		return (M)this;
	}
	
	public java.math.BigDecimal getLimitOne() {
		return get("limit_one");
	}

	public M setCreditCardOneAmountInArear(java.math.BigDecimal creditCardOneAmountInArear) {
		set("credit_card_one_amount_in_arear", creditCardOneAmountInArear);
		return (M)this;
	}
	
	public java.math.BigDecimal getCreditCardOneAmountInArear() {
		return get("credit_card_one_amount_in_arear");
	}

	public M setCreditCardBankNameTwo(java.lang.String creditCardBankNameTwo) {
		set("credit_card_bank_name_two", creditCardBankNameTwo);
		return (M)this;
	}
	
	public java.lang.String getCreditCardBankNameTwo() {
		return getStr("credit_card_bank_name_two");
	}

	public M setLimitTwo(java.math.BigDecimal limitTwo) {
		set("limit_two", limitTwo);
		return (M)this;
	}
	
	public java.math.BigDecimal getLimitTwo() {
		return get("limit_two");
	}

	public M setCreditCardTwoAmountInArear(java.math.BigDecimal creditCardTwoAmountInArear) {
		set("credit_card_two_amount_in_arear", creditCardTwoAmountInArear);
		return (M)this;
	}
	
	public java.math.BigDecimal getCreditCardTwoAmountInArear() {
		return get("credit_card_two_amount_in_arear");
	}

	public M setTotalLimit(java.math.BigDecimal totalLimit) {
		set("total_limit", totalLimit);
		return (M)this;
	}
	
	public java.math.BigDecimal getTotalLimit() {
		return get("total_limit");
	}

	public M setTotalAmountInArear(java.math.BigDecimal totalAmountInArear) {
		set("total_amount_in_arear", totalAmountInArear);
		return (M)this;
	}
	
	public java.math.BigDecimal getTotalAmountInArear() {
		return get("total_amount_in_arear");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setHomeVisitCheck(java.lang.String homeVisitCheck) {
		set("home_visit_check", homeVisitCheck);
		return (M)this;
	}
	
	public java.lang.String getHomeVisitCheck() {
		return getStr("home_visit_check");
	}

	public M setPropertyOne(java.lang.Integer propertyOne) {
		set("property_one", propertyOne);
		return (M)this;
	}
	
	public java.lang.Integer getPropertyOne() {
		return getInt("property_one");
	}

	public M setPropertyTwo(java.lang.Integer propertyTwo) {
		set("property_two", propertyTwo);
		return (M)this;
	}
	
	public java.lang.Integer getPropertyTwo() {
		return getInt("property_two");
	}

	public M setMortgageRepayDate(java.util.Date mortgageRepayDate) {
		set("mortgage_repay_date", mortgageRepayDate);
		return (M)this;
	}
	
	public java.util.Date getMortgageRepayDate() {
		return get("mortgage_repay_date");
	}

	public M setMortgageMaturityDate(java.util.Date mortgageMaturityDate) {
		set("mortgage_maturity_date", mortgageMaturityDate);
		return (M)this;
	}
	
	public java.util.Date getMortgageMaturityDate() {
		return get("mortgage_maturity_date");
	}

	public M setThirdContact(java.lang.String thirdContact) {
		set("third_contact", thirdContact);
		return (M)this;
	}
	
	public java.lang.String getThirdContact() {
		return getStr("third_contact");
	}

}
