package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCusContractMonthDetailed<M extends BaseCusContractMonthDetailed<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setMonthKey(java.lang.String monthKey) {
		set("month_key", monthKey);
		return (M)this;
	}
	
	public java.lang.String getMonthKey() {
		return getStr("month_key");
	}

	public M setMonthValue(java.math.BigDecimal monthValue) {
		set("month_value", monthValue);
		return (M)this;
	}
	
	public java.math.BigDecimal getMonthValue() {
		return get("month_value");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setMonthName(java.lang.String monthName) {
		set("month_name", monthName);
		return (M)this;
	}
	
	public java.lang.String getMonthName() {
		return getStr("month_name");
	}

	public M setContractMonthId(java.lang.Integer contractMonthId) {
		set("contract_month_id", contractMonthId);
		return (M)this;
	}
	
	public java.lang.Integer getContractMonthId() {
		return getInt("contract_month_id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

}
