package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSalSalaryStructureBaseSalaryItem<M extends BaseSalSalaryStructureBaseSalaryItem<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSalaryStructureId(java.lang.Integer salaryStructureId) {
		set("salary_structure_id", salaryStructureId);
		return (M)this;
	}
	
	public java.lang.Integer getSalaryStructureId() {
		return getInt("salary_structure_id");
	}

	public M setBaseSalaryItemId(java.lang.Integer baseSalaryItemId) {
		set("base_salary_item_id", baseSalaryItemId);
		return (M)this;
	}
	
	public java.lang.Integer getBaseSalaryItemId() {
		return getInt("base_salary_item_id");
	}

	public M setDefaultValue(java.math.BigDecimal defaultValue) {
		set("default_value", defaultValue);
		return (M)this;
	}
	
	public java.math.BigDecimal getDefaultValue() {
		return get("default_value");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

}
