package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWfFormEmployeeBaseSalaryV1<M extends BaseWfFormEmployeeBaseSalaryV1<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setEmployeeId(java.lang.String employeeId) {
		set("employee_id", employeeId);
		return (M)this;
	}
	
	public java.lang.String getEmployeeId() {
		return getStr("employee_id");
	}

	public M setBaseSalaryItemId(java.lang.Integer baseSalaryItemId) {
		set("base_salary_item_id", baseSalaryItemId);
		return (M)this;
	}
	
	public java.lang.Integer getBaseSalaryItemId() {
		return getInt("base_salary_item_id");
	}

	public M setValue(java.math.BigDecimal value) {
		set("value", value);
		return (M)this;
	}
	
	public java.math.BigDecimal getValue() {
		return get("value");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setDataKey(java.lang.String dataKey) {
		set("data_key", dataKey);
		return (M)this;
	}
	
	public java.lang.String getDataKey() {
		return getStr("data_key");
	}

}
