package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCusContractFaceTrialV1<M extends BaseCusContractFaceTrialV1<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setMaritalStatus(java.lang.Integer maritalStatus) {
		set("marital_status", maritalStatus);
		return (M)this;
	}
	
	public java.lang.Integer getMaritalStatus() {
		return getInt("marital_status");
	}

	public M setHouseholdRegistrationAdress(java.lang.String householdRegistrationAdress) {
		set("household_registration_adress", householdRegistrationAdress);
		return (M)this;
	}
	
	public java.lang.String getHouseholdRegistrationAdress() {
		return getStr("household_registration_adress");
	}

	public M setEstateCategory(java.lang.String estateCategory) {
		set("estate_category", estateCategory);
		return (M)this;
	}
	
	public java.lang.String getEstateCategory() {
		return getStr("estate_category");
	}

	public M setSpouseName(java.lang.String spouseName) {
		set("spouse_name", spouseName);
		return (M)this;
	}
	
	public java.lang.String getSpouseName() {
		return getStr("spouse_name");
	}

	public M setSpousePhone(java.lang.String spousePhone) {
		set("spouse_phone", spousePhone);
		return (M)this;
	}
	
	public java.lang.String getSpousePhone() {
		return getStr("spouse_phone");
	}

	public M setSpouseIdNum(java.lang.String spouseIdNum) {
		set("spouse_id_num", spouseIdNum);
		return (M)this;
	}
	
	public java.lang.String getSpouseIdNum() {
		return getStr("spouse_id_num");
	}

	public M setWorkUnit(java.lang.String workUnit) {
		set("work_unit", workUnit);
		return (M)this;
	}
	
	public java.lang.String getWorkUnit() {
		return getStr("work_unit");
	}

	public M setUnitNature(java.lang.String unitNature) {
		set("unit_nature", unitNature);
		return (M)this;
	}
	
	public java.lang.String getUnitNature() {
		return getStr("unit_nature");
	}

	public M setIndustry(java.lang.String industry) {
		set("industry", industry);
		return (M)this;
	}
	
	public java.lang.String getIndustry() {
		return getStr("industry");
	}

	public M setPosition(java.lang.String position) {
		set("position", position);
		return (M)this;
	}
	
	public java.lang.String getPosition() {
		return getStr("position");
	}

	public M setSalary(java.math.BigDecimal salary) {
		set("salary", salary);
		return (M)this;
	}
	
	public java.math.BigDecimal getSalary() {
		return get("salary");
	}

	public M setOtherIncome(java.math.BigDecimal otherIncome) {
		set("other_income", otherIncome);
		return (M)this;
	}
	
	public java.math.BigDecimal getOtherIncome() {
		return get("other_income");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setBankName(java.lang.String bankName) {
		set("bank_name", bankName);
		return (M)this;
	}
	
	public java.lang.String getBankName() {
		return getStr("bank_name");
	}

	public M setBankCard(java.lang.String bankCard) {
		set("bank_card", bankCard);
		return (M)this;
	}
	
	public java.lang.String getBankCard() {
		return getStr("bank_card");
	}

	public M setContractId(java.lang.Integer contractId) {
		set("contract_id", contractId);
		return (M)this;
	}
	
	public java.lang.Integer getContractId() {
		return getInt("contract_id");
	}

	public M setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
		return (M)this;
	}
	
	public java.lang.Integer getCustomerId() {
		return getInt("customer_id");
	}

}
