package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseYxdCustomerInfo<M extends BaseYxdCustomerInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCusContractId(java.lang.Integer cusContractId) {
		set("cus_contract_id", cusContractId);
		return (M)this;
	}
	
	public java.lang.Integer getCusContractId() {
		return getInt("cus_contract_id");
	}

	public M setCusName(java.lang.String cusName) {
		set("cus_name", cusName);
		return (M)this;
	}
	
	public java.lang.String getCusName() {
		return getStr("cus_name");
	}

	public M setSex(java.lang.Integer sex) {
		set("sex", sex);
		return (M)this;
	}
	
	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setMarriedState(java.lang.Integer marriedState) {
		set("married_state", marriedState);
		return (M)this;
	}
	
	public java.lang.Integer getMarriedState() {
		return getInt("married_state");
	}

	public M setIdCard(java.lang.String idCard) {
		set("id_card", idCard);
		return (M)this;
	}
	
	public java.lang.String getIdCard() {
		return getStr("id_card");
	}

	public M setQq(java.lang.String qq) {
		set("qq", qq);
		return (M)this;
	}
	
	public java.lang.String getQq() {
		return getStr("qq");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setWechat(java.lang.String wechat) {
		set("wechat", wechat);
		return (M)this;
	}
	
	public java.lang.String getWechat() {
		return getStr("wechat");
	}

	public M setHousehold(java.lang.String household) {
		set("household", household);
		return (M)this;
	}
	
	public java.lang.String getHousehold() {
		return getStr("household");
	}

	public M setLiveUser(java.lang.String liveUser) {
		set("live_user", liveUser);
		return (M)this;
	}
	
	public java.lang.String getLiveUser() {
		return getStr("live_user");
	}

	public M setNowAddress(java.lang.String nowAddress) {
		set("now_address", nowAddress);
		return (M)this;
	}
	
	public java.lang.String getNowAddress() {
		return getStr("now_address");
	}

	public M setNowHouseQuality(java.lang.String nowHouseQuality) {
		set("now_house_quality", nowHouseQuality);
		return (M)this;
	}
	
	public java.lang.String getNowHouseQuality() {
		return getStr("now_house_quality");
	}

	public M setMonthlyRent(java.math.BigDecimal monthlyRent) {
		set("monthly_rent", monthlyRent);
		return (M)this;
	}
	
	public java.math.BigDecimal getMonthlyRent() {
		return get("monthly_rent");
	}

	public M setElecAddress(java.lang.String elecAddress) {
		set("elec_address", elecAddress);
		return (M)this;
	}
	
	public java.lang.String getElecAddress() {
		return getStr("elec_address");
	}

	public M setRencentQuantity(java.lang.String rencentQuantity) {
		set("rencent_quantity", rencentQuantity);
		return (M)this;
	}
	
	public java.lang.String getRencentQuantity() {
		return getStr("rencent_quantity");
	}

	public M setInsuranceBase(java.lang.String insuranceBase) {
		set("insurance_base", insuranceBase);
		return (M)this;
	}
	
	public java.lang.String getInsuranceBase() {
		return getStr("insurance_base");
	}

	public M setInsuranceFee(java.math.BigDecimal insuranceFee) {
		set("insurance_fee", insuranceFee);
		return (M)this;
	}
	
	public java.math.BigDecimal getInsuranceFee() {
		return get("insurance_fee");
	}

	public M setHighestLinesCard(java.lang.String highestLinesCard) {
		set("highest_lines_card", highestLinesCard);
		return (M)this;
	}
	
	public java.lang.String getHighestLinesCard() {
		return getStr("highest_lines_card");
	}

	public M setCardLines(java.math.BigDecimal cardLines) {
		set("card_lines", cardLines);
		return (M)this;
	}
	
	public java.math.BigDecimal getCardLines() {
		return get("card_lines");
	}

	public M setUseTimeLimit(java.lang.String useTimeLimit) {
		set("use_time_limit", useTimeLimit);
		return (M)this;
	}
	
	public java.lang.String getUseTimeLimit() {
		return getStr("use_time_limit");
	}

	public M setIsPayOverdue(java.lang.Integer isPayOverdue) {
		set("is_pay_overdue", isPayOverdue);
		return (M)this;
	}
	
	public java.lang.Integer getIsPayOverdue() {
		return getInt("is_pay_overdue");
	}

	public M setInsuranceComp(java.lang.String insuranceComp) {
		set("insurance_comp", insuranceComp);
		return (M)this;
	}
	
	public java.lang.String getInsuranceComp() {
		return getStr("insurance_comp");
	}

	public M setInsuranceValue(java.math.BigDecimal insuranceValue) {
		set("insurance_value", insuranceValue);
		return (M)this;
	}
	
	public java.math.BigDecimal getInsuranceValue() {
		return get("insurance_value");
	}

	public M setBillNumber(java.lang.String billNumber) {
		set("bill_number", billNumber);
		return (M)this;
	}
	
	public java.lang.String getBillNumber() {
		return getStr("bill_number");
	}

	public M setInsuranceTime(java.lang.String insuranceTime) {
		set("insurance_time", insuranceTime);
		return (M)this;
	}
	
	public java.lang.String getInsuranceTime() {
		return getStr("insurance_time");
	}

	public M setFeeStyle(java.lang.Integer feeStyle) {
		set("fee_style", feeStyle);
		return (M)this;
	}
	
	public java.lang.Integer getFeeStyle() {
		return getInt("fee_style");
	}

	public M setPayedNum(java.lang.String payedNum) {
		set("payed_num", payedNum);
		return (M)this;
	}
	
	public java.lang.String getPayedNum() {
		return getStr("payed_num");
	}

	public M setNowTelephone(java.lang.String nowTelephone) {
		set("now_telephone", nowTelephone);
		return (M)this;
	}
	
	public java.lang.String getNowTelephone() {
		return getStr("now_telephone");
	}

	public M setNowAddressTele(java.lang.String nowAddressTele) {
		set("now_address_tele", nowAddressTele);
		return (M)this;
	}
	
	public java.lang.String getNowAddressTele() {
		return getStr("now_address_tele");
	}

	public M setArriveMonth(java.lang.String arriveMonth) {
		set("arrive_month", arriveMonth);
		return (M)this;
	}
	
	public java.lang.String getArriveMonth() {
		return getStr("arrive_month");
	}

	public M setProvideNum(java.lang.Integer provideNum) {
		set("provide_num", provideNum);
		return (M)this;
	}
	
	public java.lang.Integer getProvideNum() {
		return getInt("provide_num");
	}

	public M setWorkUnit(java.lang.String workUnit) {
		set("work_unit", workUnit);
		return (M)this;
	}
	
	public java.lang.String getWorkUnit() {
		return getStr("work_unit");
	}

	public M setDepartmentPosition(java.lang.String departmentPosition) {
		set("department_position", departmentPosition);
		return (M)this;
	}
	
	public java.lang.String getDepartmentPosition() {
		return getStr("department_position");
	}

	public M setUnitCharacter(java.lang.String unitCharacter) {
		set("unit_character", unitCharacter);
		return (M)this;
	}
	
	public java.lang.String getUnitCharacter() {
		return getStr("unit_character");
	}

	public M setLegalMan(java.lang.String legalMan) {
		set("legal_man", legalMan);
		return (M)this;
	}
	
	public java.lang.String getLegalMan() {
		return getStr("legal_man");
	}

	public M setUnitPhone(java.lang.String unitPhone) {
		set("unit_phone", unitPhone);
		return (M)this;
	}
	
	public java.lang.String getUnitPhone() {
		return getStr("unit_phone");
	}

	public M setUnitAddress(java.lang.String unitAddress) {
		set("unit_address", unitAddress);
		return (M)this;
	}
	
	public java.lang.String getUnitAddress() {
		return getStr("unit_address");
	}

	public M setMainBusiness(java.lang.String mainBusiness) {
		set("main_business", mainBusiness);
		return (M)this;
	}
	
	public java.lang.String getMainBusiness() {
		return getStr("main_business");
	}

	public M setSalary(java.math.BigDecimal salary) {
		set("salary", salary);
		return (M)this;
	}
	
	public java.math.BigDecimal getSalary() {
		return get("salary");
	}

	public M setPayDay(java.lang.String payDay) {
		set("pay_day", payDay);
		return (M)this;
	}
	
	public java.lang.String getPayDay() {
		return getStr("pay_day");
	}

	public M setOtherSalary(java.lang.String otherSalary) {
		set("other_salary", otherSalary);
		return (M)this;
	}
	
	public java.lang.String getOtherSalary() {
		return getStr("other_salary");
	}

	public M setBegLiveDate(java.util.Date begLiveDate) {
		set("beg_live_date", begLiveDate);
		return (M)this;
	}
	
	public java.util.Date getBegLiveDate() {
		return get("beg_live_date");
	}

	public M setEndLiveDate(java.util.Date endLiveDate) {
		set("end_live_date", endLiveDate);
		return (M)this;
	}
	
	public java.util.Date getEndLiveDate() {
		return get("end_live_date");
	}

	public M setBegServeDate(java.util.Date begServeDate) {
		set("beg_serve_date", begServeDate);
		return (M)this;
	}
	
	public java.util.Date getBegServeDate() {
		return get("beg_serve_date");
	}

	public M setEndServeDate(java.util.Date endServeDate) {
		set("end_serve_date", endServeDate);
		return (M)this;
	}
	
	public java.util.Date getEndServeDate() {
		return get("end_serve_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setNowLiveUser(java.lang.String nowLiveUser) {
		set("now_live_user", nowLiveUser);
		return (M)this;
	}
	
	public java.lang.String getNowLiveUser() {
		return getStr("now_live_user");
	}

	public M setApplyMoney(java.math.BigDecimal applyMoney) {
		set("apply_money", applyMoney);
		return (M)this;
	}
	
	public java.math.BigDecimal getApplyMoney() {
		return get("apply_money");
	}

	public M setLoanUse(java.lang.String loanUse) {
		set("loan_use", loanUse);
		return (M)this;
	}
	
	public java.lang.String getLoanUse() {
		return getStr("loan_use");
	}

	public M setApplyLoanTime(java.lang.String applyLoanTime) {
		set("apply_loan_time", applyLoanTime);
		return (M)this;
	}
	
	public java.lang.String getApplyLoanTime() {
		return getStr("apply_loan_time");
	}

	public M setIsFamilyKnow(java.lang.Integer isFamilyKnow) {
		set("is_family_know", isFamilyKnow);
		return (M)this;
	}
	
	public java.lang.Integer getIsFamilyKnow() {
		return getInt("is_family_know");
	}

}
