package com.jyd.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCusContractBlacklist<M extends BaseCusContractBlacklist<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
		return (M)this;
	}
	
	public java.lang.Integer getStoreId() {
		return getInt("store_id");
	}

	public M setCusName(java.lang.String cusName) {
		set("cus_name", cusName);
		return (M)this;
	}
	
	public java.lang.String getCusName() {
		return getStr("cus_name");
	}

	public M setCusIdNo(java.lang.String cusIdNo) {
		set("cus_id_no", cusIdNo);
		return (M)this;
	}
	
	public java.lang.String getCusIdNo() {
		return getStr("cus_id_no");
	}

	public M setCusPhone(java.lang.String cusPhone) {
		set("cus_phone", cusPhone);
		return (M)this;
	}
	
	public java.lang.String getCusPhone() {
		return getStr("cus_phone");
	}

	public M setCusBankNo(java.lang.String cusBankNo) {
		set("cus_bank_no", cusBankNo);
		return (M)this;
	}
	
	public java.lang.String getCusBankNo() {
		return getStr("cus_bank_no");
	}

	public M setValidBeginDate(java.util.Date validBeginDate) {
		set("valid_begin_date", validBeginDate);
		return (M)this;
	}
	
	public java.util.Date getValidBeginDate() {
		return get("valid_begin_date");
	}

	public M setValidEndDate(java.util.Date validEndDate) {
		set("valid_end_date", validEndDate);
		return (M)this;
	}
	
	public java.util.Date getValidEndDate() {
		return get("valid_end_date");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}
	
	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}
	
	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setEmployeeId(java.lang.Integer employeeId) {
		set("employee_id", employeeId);
		return (M)this;
	}
	
	public java.lang.Integer getEmployeeId() {
		return getInt("employee_id");
	}

}
